import { useEffect, useState } from 'react';
import { TaskCommunication, initialDraft, type Draft } from './TaskCommunication';
import { useOops, type AppData, type Route, type Task, type TaskArtifact, type TaskMaterial, type SourceReference, type TaskInquiry } from '../store';
import { makeSourceReference, materialVisible, provenanceAvailable, sourceAvailable, sourceTurn, taskSourceAvailable, taskVisible } from '../sourceAccess';
import { useViewState } from '../viewState';
import { useKeyboard } from '../mobile';
import { saveCommunicationDraft } from '../communicationLogic';
import { normalizeMoment, parseLocalMoment } from '../dateLogic';
import { taskArtifacts as artifacts, finishLocalGeneration } from '../taskLogic';
import { acceptTask, archiveTaskCompletion, beginGeneration, beginTransfer, createDeliveryCompletion, createManualCompletion, latestTaskArtifacts, outputCost, resolveTransfer, saveTaskProgress, setInquiry, taskArtifactExportAccess, taskBelongsToMe, taskFollowedByMe, taskInquiries, taskIsMyAttention, taskAttentionReason, taskOutputMode, taskPrimaryAction, taskReviewArtifacts, taskWorkKind } from '../taskWorkflow';
export { buildTaskArtifacts, finishLocalGeneration } from '../taskLogic';
import { Badge, Button, Card, Check, Chips, Empty, Field, Icon, Notice, Row, Search, SectionTitle, SelectField, Sheet, Source, Tabs } from '../ui';
import './Tasks.css';

type Artifact = TaskArtifact;
type TaskRecord = Task & { criteria?: string[]; materials?: string[]; questions?: string[]; drafts?: Record<string,Draft>; budget?: number; used?: number; failure?: string; transferFrom?: string; retryMissing?: boolean; generationSources?: SourceReference[]; generationSpace?: string };
type TaskTab = '概览'|'资料'|'成果'|'记录';
type Reader = { tab: TaskTab };
const TASK_TABS: TaskTab[] = ['概览','资料','成果','记录'];
const OUTPUT_MODES = ['资料整理','回复草稿','行动清单','文档','文档与PPT'];
const titles: Record<string,string> = {
  tasks:'任务', 'task-detail':'任务详情', 'task-accept':'核对承接', 'task-reject':'婉拒任务', 'task-transfer':'建议转交', 'task-transfer-response':'转交进展',
  'task-edit':'任务要求', 'task-create':'新建任务', 'task-plan':'助手准备', 'task-authorize':'助手准备', 'task-progress':'助手工作', 'task-failure':'补齐后继续',
  'task-budget':'助手准备', 'task-change':'修改要求', 'task-result':'成果', 'task-versions':'比较版本', 'task-preview':'成果预览', 'task-artifact-edit':'编辑成果',
  'task-send':'跟进消息', 'task-send-confirm':'核对消息', 'task-email':'审阅邮件', 'task-calendar':'审阅日程', 'task-receipt':'操作回执', 'task-history':'任务记录',
  'task-complete':'核对结果', 'task-ask':'问题与跟进', 'task-attachment':'补充资料', 'task-progress-note':'记录进展',
};
export function taskTitle(route: Route): string { return route.view === 'task-edit' && !route.id ? '新建任务' : titles[route.view] || '任务'; }
const stamp = () => new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date());
const artifactId = () => `artifact-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const closed = (t: Task) => ['已完成','已取消','已拒绝'].includes(t.status);
const accepted = (t: Task) => ['已承接','进行中','待验收'].includes(t.status);
const latestArtifacts = (t:TaskRecord) => latestTaskArtifacts(t);
const artifactLabel = (a:Artifact) => a.sourceNeedsReview?'旧来源待复核':a.needsReview?'待核对':a.reviewedAt?'已核对':'未核对';
const taskState = (t:Task) => closed(t)?t.status:t.sourceNeedsReview?'来源待核对':t.status==='已承接'?'待做':t.status;
const readerKey = (space:string,id:string) => `task-reader:${space}:${id}`;
const deliveryKey = (space:string,t:TaskRecord) => `task-delivery:${space}:${t.id}:${t.version}`;
const usable = (v:string) => !!v.trim() && !/待选择|请选择|未设置|待确认|^未知$/.test(v.trim());
const validMoment = parseLocalMoment;
function dueText(v:string) { return !v||v==='无固定期限'?'无固定期限':v.replace('T',' ').replace(/^\d{4}-/,'').replace('-','月').replace(' ','日 '); }
function visibleSession(data:AppData,id:string) { const s=data.sessions.find(x=>x.id===id);return !!s&&(data.settings.space==='我的空间'||!!data.settings.toggles['shared-'+id]&&(data.settings.retention['session-space:'+id]||'Oops 产品团队')===data.settings.space); }
function materialsAvailable(data:AppData,t:TaskRecord) { return (t.materialRefs||[]).every(m=>!m.needsReview&&sourceAvailable(data,m)&&(!m.memoryId||data.memories.some(x=>x.id===m.memoryId&&!x.deleted&&x.confirmed&&!x.needsReview&&!x.tags.includes('待复核')&&provenanceAvailable(data,x.sources)))); }
const inquiries = taskInquiries;
function useTaskActions(t:TaskRecord) {
  const {data,update,navigate,toast}=useOops();
  function patch(change:Partial<TaskRecord>,activity?:string) { update(current=>({...current,tasks:current.tasks.map(x=>x.id===t.id?{...x,...change,activities:activity?[...x.activities,`${stamp()} · ${activity}`]:x.activities}:x)})); }
  function go(view:string,mode?:string) { navigate({view,id:t.id,mode}); }
  function apply(helper:(current:AppData)=>{data:AppData;error?:string},success?:string) { const result=helper(data);if(result.error){toast(result.error);return false;}update(current=>{const fresh=helper(current);if(fresh.error){toast(fresh.error);return current;}return fresh.data;});if(success)toast(success);return true; }
  function start(retry=false) {
    const result=beginGeneration(data,t.id,{retry});if(result.error||!result.token){toast(result.error||'准备未启动');return;}let token=result.token,cost=result.cost||0;
    update(current=>{const fresh=beginGeneration(current,t.id,{token,retry});if(fresh.error){toast(fresh.error);token='';return current;}cost=fresh.cost||cost;return fresh.data;});
    if(!token)return;setTimeout(()=>update(current=>finishLocalGeneration(current,t.id,token,cost)),2400);go('task-progress');
  }
  return {patch,go,start,apply};
}
function TaskSource({task}:{task:TaskRecord}) {
  const {data,navigate}=useOops();const session=data.sessions.find(s=>s.id===task.sourceSession),turn=sourceTurn(data,task);
  if(!task.sourceSession)return null;
  if(!session||!sourceAvailable(data,task))return <Notice tone="warning">原话已变化，先重新核对来源。</Notice>;
  return <Source title={session.title} time={turn?.time||task.sourceTime} onClick={()=>navigate({view:'session-transcript',id:session.id,mode:turn?.id||task.sourceId||task.sourceTime})}/>;
}
function TaskCard({task:t}:{task:TaskRecord}) {
  const {data,navigate}=useOops(),reason=taskBelongsToMe(data,t)?taskAttentionReason(t):taskIsMyAttention(data,t)?'到时间跟进这项工作':null,action=taskBelongsToMe(data,t)?taskPrimaryAction(t):{label:'查看跟进',view:'task-ask'};
  return <Card className="task-card task-list-card" onClick={()=>navigate({view:'task-detail',id:t.id})}><div className="section-title"><Badge tone={closed(t)?'gray':'purple'}>{taskState(t)}</Badge>{t.priority==='高'&&<Badge tone="rose">优先</Badge>}</div><h3>{t.title}</h3><p className="meta">{t.owner}负责 · {dueText(t.due)}</p><div className="task-card-next"><Icon name={reason?'flag':'arrow-right'} size={17}/><span>{reason||action?.label||'查看工作记录'}</span></div>{t.aiStatus==='准备中'&&<p className="meta task-assistant-line"><Icon name="sparkle" size={14}/>助手正在准备</p>}</Card>;
}
function dateGroup(t:TaskRecord) { if(closed(t))return '已结束';const due=validMoment(t.due),now=Date.now(),end=new Date();end.setHours(23,59,59,999);return due===undefined?'无固定期限':due<now?'已逾期':due<=end.getTime()?'今天':'之后'; }
function attentionGroup(t:TaskRecord) { if(t.sourceNeedsReview)return '来源与要求待核对';if(t.status==='待承接')return '需要决定';if(t.status==='待转交')return '需要跟进';if(t.aiStatus==='失败'||inquiries(t).some(x=>x.status!=='已解决'))return '需要补齐与跟进';return t.needsReview||t.status==='待验收'?'成果与结果待核对':'需要跟进'; }
function assistantGroup(t:TaskRecord) { return t.aiStatus==='准备中'?'正在准备':t.aiStatus==='草稿完成'?'草稿就绪':t.aiStatus==='失败'?'需要处理':t.aiStatus==='已暂停'||t.aiStatus==='已停止'?'已暂停与停止':'等待允许'; }
function TaskList() {
  const {data,route,navigate}=useOops();const key='task-list:'+data.settings.space;const [query,setQuery]=useViewState(key+':query',''),[mode,setMode]=useViewState(key+':mode',route.mode||'待我处理'),[relation,setRelation]=useViewState(key+':relation:'+mode,mode==='待我处理'?'全部关系':'我负责'),[filter,setFilter]=useViewState(key+':status','未结束'),[priority,setPriority]=useViewState(key+':priority','全部优先级'),[filters,setFilters]=useState(false);
  useEffect(()=>{if(route.mode&&['待我处理','我的待办','助手工作'].includes(route.mode))setMode(route.mode);},[route.mode,setMode]);
  const mine=(v:string)=>['我',data.settings.name].includes(v),all=data.tasks.filter(t=>taskVisible(data,t)) as TaskRecord[];
  const related=(t:TaskRecord)=>relation==='我提出'?mine(t.requester):relation==='我跟进'?taskFollowedByMe(data,t):relation==='全部关系'||taskBelongsToMe(data,t);
  const list=all.filter(related).filter(t=>mode==='待我处理'?taskIsMyAttention(data,t):mode==='助手工作'?t.aiStatus!=='未启动':true).filter(t=>filter==='全部状态'||(filter==='已结束'?closed(t):!closed(t))).filter(t=>priority==='全部优先级'||t.priority===priority.replace('优先级','')).filter(t=>`${t.title} ${t.description} ${t.requester} ${t.owner}`.toLowerCase().includes(query.trim().toLowerCase()));
  const order=mode==='待我处理'?['来源与要求待核对','需要决定','需要补齐与跟进','成果与结果待核对','需要跟进']:mode==='助手工作'?['正在准备','草稿就绪','需要处理','等待允许','已暂停与停止']:['已逾期','今天','之后','无固定期限','已结束'];
  const group=(t:TaskRecord)=>mode==='待我处理'?(taskBelongsToMe(data,t)?attentionGroup(t):'需要跟进'):mode==='助手工作'?assistantGroup(t):dateGroup(t);
  const sort=(a:TaskRecord,b:TaskRecord)=>(validMoment(a.nextFollowUp||a.due)??Infinity)-(validMoment(b.nextFollowUp||b.due)??Infinity)||({高:0,中:1,低:2}[a.priority]-{高:0,中:1,低:2}[b.priority]);
  return <div className="stack task-list"><div className="section-title"><div><h1 className="title">把事情往前推进</h1><p className="meta">{all.filter(t=>mine(t.owner)&&!closed(t)).length}项我的工作</p></div><Button tone="quiet" icon="plus" onClick={()=>navigate({view:'task-create'})}>新建</Button></div><Tabs items={['待我处理','我的待办','助手工作']} value={mode} onChange={setMode}/><div className="task-search-row"><Search value={query} onChange={setQuery} placeholder="搜索工作或提出者"/><button className="task-filter-button" aria-label="任务筛选" onClick={()=>setFilters(true)}><Icon name="sliders-horizontal"/><span>筛选</span></button></div>{(relation!=='我负责'||filter!=='未结束'||priority!=='全部优先级')&&<p className="meta">{relation} · {filter} · {priority}</p>}{order.map(name=>{const items=list.filter(t=>group(t)===name).sort(sort);return items.length?<section className="stack task-group" key={name}><SectionTitle>{name} <span className="meta">{items.length}</span></SectionTitle>{items.map(t=><TaskCard key={t.id} task={t}/>)}</section>:null})}{!list.length&&<Empty title={mode==='待我处理'?'当前没有需要你处理的事':'这里暂时没有工作'} body={query?'换个关键词，或调整筛选':'创建一个待办，或从会话行动继续推进'} icon="check-circle" action="新建待办" onAction={()=>navigate({view:'task-create'})}/>}<Sheet open={filters} onClose={()=>setFilters(false)} title="筛选任务"><div className="stack"><SelectField label="与我的关系" value={relation} onChange={setRelation} options={['我负责','我提出','我跟进','全部关系']}/><SelectField label="工作状态" value={filter} onChange={setFilter} options={['未结束','已结束','全部状态']}/><SelectField label="优先级" value={priority} onChange={setPriority} options={['全部优先级','高优先级','中优先级','低优先级']}/><Button onClick={()=>setFilters(false)}>查看{list.length}项工作</Button><Button tone="quiet" onClick={()=>{setRelation(mode==='待我处理'?'全部关系':'我负责');setFilter('未结束');setPriority('全部优先级');}}>恢复默认</Button></div></Sheet></div>;
}
export function TaskTabBar() {
  const {data,route}=useOops(),keyboard=useKeyboard();const t=data.tasks.find(x=>x.id===route.id);const [reader,setReader]=useViewState<Reader>(readerKey(data.settings.space,route.id||'missing'),{tab:'概览'});
  useEffect(()=>{if(route.view==='task-detail'&&TASK_TABS.includes(route.mode as TaskTab))setReader({tab:route.mode as TaskTab});},[route.id,route.mode,route.view]);
  if(route.view!=='task-detail'||!t||!taskVisible(data,t))return null;
  return <div className="task-tab-bar"><Tabs items={TASK_TABS} value={TASK_TABS.includes(reader.tab)?reader.tab:'概览'} onChange={value=>{keyboard.hide();setReader({tab:value as TaskTab});}}/></div>;
}
export function TaskPrimaryFooter() {
  const {data,update,route,navigate,toast}=useOops(),keyboard=useKeyboard();const t=data.tasks.find(x=>x.id===route.id) as TaskRecord|undefined;const [more,setMore]=useState(false),[cancel,setCancel]=useState(false),[cancelReason,setCancelReason]=useViewState(`task-cancel:${data.settings.space}:${route.id||''}`,'');const [,setReader]=useViewState<Reader>(readerKey(data.settings.space,route.id||'missing'),{tab:'概览'});
  if(route.view!=='task-detail'||!t||!taskVisible(data,t))return null;
  const owned=taskBelongsToMe(data,t),sourceInvalid=owned&&!closed(t)&&(!taskSourceAvailable(data,t)||t.sourceNeedsReview),action=closed(t)?null:!owned?{label:taskFollowedByMe(data,t)?'查看跟进':'查看工作记录',view:taskFollowedByMe(data,t)?'task-ask':'task-detail',mode:'记录'}:sourceInvalid?{label:'重新核对来源与要求',view:'task-edit'}:taskPrimaryAction(t);
  const go=(view:string,mode?:string)=>{keyboard.hide();setMore(false);navigate({view,id:t.id,mode});};
  function primary(){if(!action){setReader({tab:'记录'});return;}if(action.view==='task-detail'){setReader({tab:(TASK_TABS.includes(action.mode as TaskTab)?action.mode:'概览') as TaskTab});return;}go(action.view,action.mode);}
  return <><div className="task-primary-actions"><Button onClick={primary} >{action?.label||'查看完成记录'}</Button><button className="task-more-button" aria-label="更多任务操作" onClick={()=>{keyboard.hide();setMore(true)}}><Icon name="dots-three"/></button></div><Sheet open={more} onClose={()=>setMore(false)} title="更多操作"><div className="stack"><Card>{owned&&!closed(t)&&<Row title="记录实际进展" icon="pencil-line" onClick={()=>go('task-progress-note')}/>}{owned&&<Row title="修改要求与期限" icon="list-checks" onClick={()=>go('task-edit')}/>}{owned&&!closed(t)&&<Row title={t.aiStatus==='准备中'?'查看助手进度':'让助手帮我准备'} icon="sparkle" onClick={()=>go(t.aiStatus==='准备中'?'task-progress':'task-plan')}/>}<Row title="问题与下一次跟进" icon="chat-circle-text" onClick={()=>go('task-ask')}/>{owned&&<Row title="补充资料" icon="paperclip" onClick={()=>go('task-attachment')}/>}{owned&&t.status==='待承接'&&<Row title="婉拒这项请求" icon="x-circle" onClick={()=>go('task-reject')}/>} {owned&&!closed(t)&&<Row title={t.status==='待转交'?'查看转交回应':'建议转交'} icon="user-switch" onClick={()=>go(t.status==='待转交'?'task-transfer-response':'task-transfer')}/>}<Row title="草拟跟进消息" icon="chat-circle-text" onClick={()=>go('task-send')}/><Row title="安排跟进日程" icon="calendar-blank" onClick={()=>go('task-calendar')}/><Row title="比较成果版本" icon="clock-counter-clockwise" onClick={()=>go('task-versions')}/></Card>{owned&&!closed(t)&&<Button tone="danger" onClick={()=>{setMore(false);setCancel(true)}}>取消这项工作</Button>}</div></Sheet><Sheet open={cancel} onClose={()=>setCancel(false)} title="取消工作"><div className="stack"><Field label="取消原因" value={cancelReason} onChange={setCancelReason} multiline/><Button tone="danger" onClick={()=>{if(!cancelReason.trim())return toast('填写取消原因');update(current=>({...current,tasks:current.tasks.map(x=>x.id===t.id?{...x,status:'已取消',aiStatus:'已停止',authorized:false,generationToken:undefined,generationSnapshot:undefined,generationSources:undefined,generationSpace:undefined,activities:[...x.activities,`${stamp()} · 取消工作：${cancelReason}`]}:x)}));setCancel(false);toast('工作已取消，成果与记录保留');}}>确认取消</Button><Button tone="quiet" onClick={()=>setCancel(false)}>继续工作</Button></div></Sheet></>;
}
function Detail({task:t}:{task:TaskRecord}) {
  const {data,navigate}=useOops(),{go}=useTaskActions(t),[reader]=useViewState<Reader>(readerKey(data.settings.space,t.id),{tab:'概览'});const tab=TASK_TABS.includes(reader.tab)?reader.tab:'概览';
  if(tab==='资料')return <TaskMaterials task={t}/>;if(tab==='成果')return <Result task={t} embedded/>;if(tab==='记录')return <History task={t}/>;
  const reason=taskAttentionReason(t),open=inquiries(t).filter(x=>x.status!=='已解决'),relation=t.relatedSessionId||t.sourceSession;
  return <div className="stack task-detail-content"><Card className="task-hero"><div className="section-title"><Badge>{taskState(t)}</Badge><Badge tone="gray">{taskWorkKind(t)}</Badge></div><h1 className="title">{t.title}</h1>{t.description&&<p>{t.description}</p>}<div className="task-facts"><span><small>负责人</small><strong>{t.owner}</strong></span><span><small>期限</small><strong>{dueText(t.due)}</strong></span></div><p className="meta">{t.origin||(['我',data.settings.name].includes(t.requester)?'本人待办':`${t.requester}提出`)} · {t.priority}优先级</p><TaskSource task={t}/></Card>{reason&&<Notice tone={t.sourceNeedsReview?'warning':'soft'}><strong>{reason}</strong>{t.nextFollowUp&&<p className="meta">下次跟进 {dueText(t.nextFollowUp)}</p>}</Notice>}{t.status==='已完成'&&t.completion&&<Card><SectionTitle>完成结果</SectionTitle><p className="task-body">{t.completion.summary}</p>{t.completion.remaining&&<p className="meta">后续：{t.completion.remaining}</p>}</Card>}<Card><Row title="工作要求" subtitle={t.criteria?.length?`${t.criteria.length}项验收标准`:'可补充要求、期限与验收'} icon="list-checks" onClick={()=>go('task-edit')}/>{t.criteria?.map(c=><p className="task-criterion" key={c}><Icon name="check-square" size={16}/>{c}</p>)}</Card>{open.length>0&&<Card><SectionTitle action="查看" onAction={()=>go('task-ask')}>待确认问题</SectionTitle>{open.slice(0,2).map(q=><div className="task-inquiry-summary" key={q.id}><Badge tone="gray">{q.status}</Badge><p>{q.question}</p>{q.nextFollowUp&&<small className="meta">{dueText(q.nextFollowUp)}跟进</small>}</div>)}</Card>}<Card><Row title={t.aiStatus==='未启动'?'需要助手帮忙？':`助手 · ${t.aiStatus}`} subtitle={t.aiStatus==='草稿完成'?'草稿已保存，工作进展由你确认':t.aiStatus==='准备中'?'按已确认范围准备，实际工作继续由你负责':'整理资料、起草回复或准备交付物'} icon="sparkle" onClick={()=>go(t.aiStatus==='准备中'?'task-progress':t.aiStatus==='草稿完成'?'task-result':'task-plan')}/><Row title="记录实际进展" subtitle="记录已做的事与下一次跟进" icon="pencil-line" onClick={()=>go('task-progress-note')}/></Card>{t.activities.length>0&&<p className="meta task-last-activity">最近：{t.activities[t.activities.length-1]}</p>}{t.sourceMemoryId&&data.memories.some(m=>m.id===t.sourceMemoryId&&!m.deleted)&&<Button tone="quiet" onClick={()=>navigate({view:'memory-detail',id:t.sourceMemoryId})}>查看保存的来源</Button>}{relation&&visibleSession(data,relation)&&<Button tone="quiet" onClick={()=>navigate({view:'session-detail',id:relation,mode:'任务'})}>回到本会话行动</Button>}</div>;
}
function Accept({task:t}:{task:TaskRecord}) {
  const {data}=useOops(),{apply,go}=useTaskActions(t);const key=`task-accept:${data.settings.space}:${t.id}:${t.version}`;const [due,setDue]=useViewState(key+':due',t.due.replace('T',' ')),[checked,setChecked]=useViewState(key+':checked',false),[error,setError]=useState('');
  function accept(){if(t.status!=='待承接')return go(t.status==='待转交'?'task-transfer-response':'task-detail');if(!checked)return setError('请核对本人责任');if(due.trim()&&due!=='无固定期限'&&validMoment(due)===undefined)return setError('期限需为有效日期时间，或留空');if(!taskSourceAvailable(data,t))return go('task-edit');if(apply(current=>acceptTask(current,t.id,{due}),'已承接，助手尚未启动'))go('task-detail');}
  if(t.status!=='待承接')return <Empty title={t.status==='待转交'?'先处理转交回应':'当前工作无需重复承接'} body={t.status==='待转交'?'对方回应前仍保留原负责人，请先查看这次转交。':'回到详情继续当前工作。'} action={t.status==='待转交'?'查看转交进展':'返回任务'} onAction={()=>go(t.status==='待转交'?'task-transfer-response':'task-detail')}/>;
  return <div className="stack"><Card><Badge>来自{t.requester}</Badge><h2>{t.title}</h2>{t.description&&<p>{t.description}</p>}<p className="meta">由我（{data.settings.name}）负责</p><TaskSource task={t}/></Card><Field label="期限（可留空）" value={due==='无固定期限'?'':due} onChange={setDue} placeholder="2026-10-09 17:00" hint="按当前设备本地时间"/><Check label="已核对目标，我负责这项工作" value={checked} onChange={setChecked}/>{error&&<p className="error-text">{error}</p>}<Button onClick={accept}>确认承接</Button><Button tone="secondary" onClick={()=>go('task-edit')}>先补充要求</Button><div className="action-grid"><Button tone="quiet" onClick={()=>go('task-transfer')}>建议转交</Button><Button tone="quiet" onClick={()=>go('task-reject')}>婉拒</Button></div></div>;
}
function Reject({task:t}:{task:TaskRecord}) {
  const {data,toast}=useOops(),{patch,go}=useTaskActions(t);const [reason,setReason]=useViewState(`task-reject:${data.settings.space}:${t.id}`,''),[error,setError]=useState('');
  return <div className="stack"><Card><h2>{t.title}</h2><p className="meta">给{t.requester}一个明确回应</p></Card><Field label="婉拒原因" value={reason} onChange={setReason} multiline/>{error&&<p className="error-text">{error}</p>}<Button tone="danger" onClick={()=>{if(closed(t))return go('task-detail');if(!reason.trim())return setError('补充婉拒原因');patch({status:'已拒绝',aiStatus:'已停止',authorized:false,generationToken:undefined},`婉拒：${reason}`);toast('已保存回应');go('task-detail');}}>确认婉拒</Button><Button tone="secondary" onClick={()=>go('task-transfer')}>改为建议转交</Button></div>;
}
function Transfer({task:t,response=false}:{task:TaskRecord;response?:boolean}) {
  const {data,toast}=useOops(),{go,apply,patch}=useTaskActions(t);const key=`task-transfer:${data.settings.space}:${t.id}`,people=data.people.filter(p=>p.name!=='待确认'&&(data.settings.space==='我的空间'||p.shared));const [person,setPerson]=useViewState(key+':person',t.transferRequest?.to||t.transferTo||''),[reason,setReason]=useViewState(key+':reason',''),[follow,setFollow]=useViewState(key+':follow',t.nextFollowUp||''),[error,setError]=useState('');const request=t.transferRequest;
  function resolve(answer:'同意'|'婉拒'|'撤回'){if(!request)return setError('这笔旧请求缺少记录，请撤回后重新选择接收人');if(apply(current=>resolveTransfer(current,t.id,request.id,answer),answer==='同意'?'已记录演示同意':answer==='婉拒'?'已恢复原工作状态':'转交请求已撤回'))go('task-detail');}
  if(response)return <div className="stack"><Card><Badge>{request?.status||'旧转交请求'}</Badge><h2>{t.title}</h2><p>建议由{request?.to||t.transferTo||'待选择的人'}接手</p><p className="meta">原负责人 {request?.fromOwner||t.owner}</p>{request?.reason&&<p>{request.reason}</p>}{t.nextFollowUp&&<p className="meta">跟进 {dueText(t.nextFollowUp)}</p>}</Card>{request?.status==='待回应'?<><p className="meta">以下回应仅用于本地示例，没有向接收人发送请求。</p><Button onClick={()=>resolve('同意')}>演示接收人同意</Button><Button tone="secondary" onClick={()=>resolve('婉拒')}>演示接收人婉拒</Button><Button tone="quiet" onClick={()=>resolve('撤回')}>撤回请求</Button></>:<Button onClick={()=>go('task-detail')}>返回任务</Button>}{!request&&<Button tone="secondary" onClick={()=>{patch({owner:'我',status:'已承接',transferTo:undefined,authorized:false,generationToken:undefined,generationSnapshot:undefined},'本人确认撤回旧转交请求，并继续负责这项工作');toast('已撤回旧请求，由本人继续负责');go('task-detail')}}>撤回旧请求，由我继续负责</Button>}{error&&<p className="error-text">{error}</p>}</div>;
  const labels=people.map(p=>`${p.name}${p.company?' · '+p.company:''} · ${p.id}`),selected=people.find(p=>p.name===person);
  return <div className="stack"><Card><h2>{t.title}</h2><p className="meta">当前由{t.owner}负责</p></Card><SelectField label="建议接收人" value={selected?labels[people.indexOf(selected)]:'先选择接收人'} options={['先选择接收人',...labels]} onChange={v=>setPerson(people[labels.indexOf(v)]?.name||'')}/><Field label="转交说明" value={reason} onChange={setReason} multiline/><Field label="下一次跟进（可留空）" value={follow} onChange={setFollow} placeholder="2026-10-09 10:00" hint="按当前设备本地时间"/>{error&&<p className="error-text">{error}</p>}<Button onClick={()=>{if(!usable(person)||person===t.owner||person===data.settings.name)return setError('选择另一位明确的接收人');if(!reason.trim())return setError('补充转交说明');if(follow.trim()&&validMoment(follow)===undefined)return setError('跟进时间需为有效日期时间');if(apply(current=>beginTransfer(current,t.id,{to:person,reason,nextFollowUp:normalizeMoment(follow)}),'转交请求已记录'))go('task-transfer-response');}}>记录转交请求</Button><p className="meta">对方确认前保留原责任。这里只记录本地请求。</p></div>;
}
function Requirements({task}:{task?:TaskRecord}) {
  const {data,update,navigate,toast}=useOops();const key=`task-requirements:${data.settings.space}:${task?.id||'new'}:${task?.version||0}`;
  const [title,setTitle]=useViewState(key+':title',task?.title||''),[goal,setGoal]=useViewState(key+':goal',task?.description||''),[due,setDue]=useViewState(key+':due',task?.due==='无固定期限'?'':task?.due.replace('T',' ')||''),[priority,setPriority]=useViewState<string>(key+':priority',task?.priority||'中'),[kind,setKind]=useViewState<string>(key+':kind',task?taskWorkKind(task):'行动'),[criteria,setCriteria]=useViewState(key+':criteria',task?.criteria?.join('\n')||''),[expanded,setExpanded]=useViewState(key+':expanded',!!task),[error,setError]=useState(''),[checked,setChecked]=useViewState(key+':checked',false);
  const [sessionId,setSessionId]=useViewState(key+':session',task?.sourceSession||''),[turnId,setTurnId]=useViewState(key+':source',sourceTurn(data,task||{})?.id||'');
  const sessions=data.sessions.filter(s=>visibleSession(data,s.id)),session=sessions.find(s=>s.id===sessionId),turns=session?.transcript.filter(x=>data.settings.space==='我的空间'||!x.private)||[],turn=turns.find(x=>x.id===turnId),sourceReview=!!task&&(!!task.sourceNeedsReview||!taskSourceAvailable(data,task)||!materialsAvailable(data,task)),sessionLabels=sessions.map(s=>`${s.title} · ${s.date} · ${s.id.slice(-6)}`),turnLabels=turns.map(x=>`${x.time||'无时间'} · ${x.speaker}：${x.text.slice(0,24)} · ${x.id}`);
  function save(){
    if(!title.trim())return setError('填写任务名称');if(due.trim()&&validMoment(due)===undefined)return setError('期限需为有效日期时间，或留空');if(kind==='交付'&&!criteria.trim())return setError('交付任务需说明验收标准');if(sourceReview&&!checked)return setError('请核对当前来源与资料');if(sourceReview&&task?.sourceSession&&!turn)return setError('原话引用不能清空，选择有效片段');
    const refs=task?.materialRefs?.map(m=>{const memory=m.memoryId?data.memories.find(x=>x.id===m.memoryId):undefined;return {...m,...(memory?{body:memory.body,sourceSession:memory.sourceSession,sourceId:memory.sourceId,sourceTime:memory.sourceTime}:{}),needsReview:false}}),evidence=sourceReview&&turn?{sourceSession:session!.id,sourceId:turn.id,sourceTime:turn.time}:{},sources=task?.sources?.map(ref=>makeSourceReference(data,sourceReview&&turn&&ref.kind==='session'&&ref.id===task.sourceSession&&(ref.sourceId===task.sourceId||ref.sourceTime===task.sourceTime)?{kind:'session',id:session!.id,sourceId:turn.id,sourceTime:turn.time}:{...ref,fingerprint:undefined}));
    const candidate=task?{...task,...evidence,materialRefs:refs,sources,sourceNeedsReview:false}:undefined;if(sourceReview&&candidate&&!taskSourceAvailable(data,candidate))return setError('附入资料仍失效，先替换或移除再核对');
    const changed=!!task&&(title.trim()!==task.title||goal.trim()!==task.description||criteria.trim()!==(task.criteria||[]).join('\n')||kind!==taskWorkKind(task)),id=task?.id||`TASK-${Date.now().toString(36)}`;
    const fields:Partial<TaskRecord>={title:title.trim(),description:goal.trim(),due:normalizeMoment(due)||'无固定期限',priority:priority as Task['priority'],workKind:kind as '行动'|'交付',criteria:criteria.split('\n').map(v=>v.trim()).filter(Boolean),...(sourceReview?{...evidence,materialRefs:refs,sources,sourceNeedsReview:false}:{}),...(task&&(changed||sourceReview)?{...archiveTaskCompletion(task),version:task.version+1,authorized:false,generationToken:undefined,generationSnapshot:undefined,aiStatus:'待授权',needsReview:artifacts(task).length>0,deliveryArtifactIds:undefined,status:task.status==='已完成'||accepted(task)?'已承接':task.status,artifacts:artifacts(task).map(a=>({...a,needsReview:true}))}:{})};
    update(current=>({...current,tasks:task?current.tasks.map(x=>x.id===id?{...x,...fields,activities:[...x.activities,`${stamp()} · ${sourceReview?'重新核对要求与有效来源':'更新工作要求'}`]}:x):[...current.tasks,{id,title:title.trim(),description:goal.trim(),owner:'我',requester:data.settings.name,due:normalizeMoment(due)||'无固定期限',priority:priority as Task['priority'],workKind:kind as '行动'|'交付',origin:'本人创建',criteria:fields.criteria,status:'已承接',aiStatus:'未启动',activities:[`${stamp()} · 本人新建待办`],results:[],version:1}],settings:sourceReview?{...current.settings,retention:{...current.settings.retention,['task-space:'+id]:'我的空间'}}:!task?{...current.settings,retention:{...current.settings.retention,['task-space:'+id]:current.settings.space}}:current.settings}));
    if(!task){setTitle('');setGoal('');setDue('');setCriteria('');setExpanded(false);}toast(sourceReview?'已核对当前来源，助手需重新允许':task?'要求已保存':'待办已创建');navigate({view:'task-detail',id});
  }
  return <div className="stack">{sourceReview&&<><Notice tone="warning">旧成果保留，更新有效来源后再继续。</Notice>{task?.sourceSession&&<><SelectField label="来源会话" value={session?sessionLabels[sessions.indexOf(session)]:'先选择会话'} options={['先选择会话',...sessionLabels]} onChange={v=>{setSessionId(sessions[sessionLabels.indexOf(v)]?.id||'');setTurnId('');setChecked(false)}}/><SelectField label="有效原话" value={turn?turnLabels[turns.indexOf(turn)]:'先选择片段'} options={['先选择片段',...turnLabels]} onChange={v=>{setTurnId(turns[turnLabels.indexOf(v)]?.id||'');setChecked(false)}}/>{turn&&<Card><p className="task-body">{turn.text}</p></Card>}</>}</>}<Field label="想完成什么？" value={title} onChange={setTitle} placeholder="例如：核实库存，或约一次讨论"/><SelectField label="工作类型" value={kind} onChange={setKind} options={['行动','交付']}/><Button tone="quiet" icon={expanded?'caret-up':'caret-down'} onClick={()=>setExpanded(!expanded)}>{expanded?'收起补充信息':'补充要求、期限与优先级'}</Button>{(expanded||kind==='交付')&&<><Field label="目标与要求（可留空）" value={goal} onChange={setGoal} multiline/><Field label="期限（可留空）" value={due} onChange={setDue} placeholder="2026-10-09 17:00" hint="按当前设备本地时间"/><SelectField label="优先级" value={priority} onChange={setPriority} options={['高','中','低']}/><Field label={kind==='交付'?'验收标准':'完成标准（可留空）'} value={criteria} onChange={setCriteria} multiline hint="每行一项"/></>}{sourceReview&&<Check label="已核对当前要求、来源与资料" value={checked} onChange={setChecked}/>} {error&&<p className="error-text">{error}</p>}<Button onClick={save}>{task?'保存要求':'创建待办'}</Button>{sourceReview&&<Button tone="secondary" onClick={()=>navigate({view:'task-attachment',id:task!.id})}>先处理失效资料</Button>}</div>;
}
function ProgressNote({task:t}:{task:TaskRecord}) {
  const {data}=useOops(),{apply,go}=useTaskActions(t),key=`task-progress-note:${data.settings.space}:${t.id}`;const [note,setNote]=useViewState(key+':note',''),[follow,setFollow]=useViewState(key+':follow',t.nextFollowUp||''),[error,setError]=useState('');
  function save(){if(closed(t))return setError('工作已结束，先回详情查看记录');if(t.status==='待承接')return go('task-accept');if(!taskSourceAvailable(data,t))return go('task-edit');if(!note.trim())return setError('填写实际进展');if(follow.trim()&&validMoment(follow)===undefined)return setError('填写有效跟进时间');if(apply(current=>saveTaskProgress(current,t.id,{note,nextFollowUp:follow}),'实际进展已保存')){setNote('');go('task-detail');}}
  return <div className="stack"><Card><h2>{t.title}</h2><p className="meta">{taskState(t)}</p></Card>{t.status==='待转交'&&<Notice>对方回应前，仍由你负责。记录进展会保留当前转交请求。</Notice>}<Field label="已经推进了什么？" value={note} onChange={setNote} multiline placeholder="记录真实进展、结果或阻碍"/><Field label="下一次跟进（可留空）" value={follow} onChange={setFollow} placeholder="2026-10-09 10:00" hint="按当前设备本地时间"/>{error&&<p className="error-text">{error}</p>}<Button onClick={save}>保存实际进展</Button>{t.status==='待转交'?<Button tone="secondary" onClick={()=>go('task-transfer-response')}>查看转交回应</Button>:<Button tone="secondary" onClick={()=>go('task-complete',taskWorkKind(t)==='行动'?'人工完成':'交付验收')}>这项工作已完成</Button>}</div>;
}
function AssistantSetup({task:t}:{task:TaskRecord}) {
  const {data,update,toast}=useOops(),{patch,go}=useTaskActions(t);const key=`task-prepare:${data.settings.space}:${t.id}:${t.version}`,refs=t.materialRefs||[];
  const [mode,setMode]=useViewState<string>(key+':mode',taskOutputMode(t)),[limit,setLimit]=useViewState(key+':limit',String(t.budget??40)),[includeSource,setIncludeSource]=useViewState(key+':source',t.scope?.includeSource!==false),[ids,setIds]=useViewState<string[]>(key+':materials',t.scope?.materialIds||refs.map(m=>m.id)),[read,setRead]=useViewState(key+':read',false),[draft,setDraft]=useViewState(key+':draft',false),[error,setError]=useState('');const cost=outputCost(mode),source=sourceTurn(data,t),selected=refs.filter(m=>ids.includes(m.id));
  function changed(){setRead(false);setDraft(false);setError('');if(t.aiStatus==='准备中')patch({aiStatus:'待授权',generationToken:undefined,generationSnapshot:undefined,authorized:false},'准备配置改变，停止旧请求并撤回授权');}
  function configured(current:AppData,startNow:boolean,token?:string){
    const actual=current.tasks.find(x=>x.id===t.id) as TaskRecord|undefined;if(!actual)return {data:current,error:'任务已移除'};if(closed(actual))return {data:current,error:'工作已结束，不能继续准备'};if(!accepted(actual))return {data:current,error:'先确认承接这项工作'};
    const scope={sources:[includeSource&&t.sourceSession?'所选任务原话':'本人任务要求',...selected.map(m=>m.title)].join('、'),destination:'我的个人成果',space:current.settings.space,materialIds:ids.filter(id=>refs.some(m=>m.id===id)),includeSource};
    const next:AppData={...current,tasks:current.tasks.map(x=>x.id===t.id?{...x,scope,outputMode:mode,budget:Number(limit),authorized:startNow,aiStatus:startNow?'未启动':'待授权',generationToken:undefined,generationSnapshot:undefined,activities:[...x.activities,`${stamp()} · ${startNow?'允许所选资料并准备个人草稿':'保存助手配置，尚未允许准备'}`]}:x)};
    return startNow?beginGeneration(next,t.id,{token}):{data:next};
  }
  function save(startNow:boolean){
    if(t.aiStatus==='准备中')return setError('先停止当前准备，再确认新范围');if(!accepted(t))return go('task-accept');const budget=Number(limit);if(!Number.isFinite(budget)||budget<(t.used??0)+(startNow?cost:0))return setError('额度上限需覆盖已用额度与本次准备');if(startNow&&(!read||!draft))return setError('勾选资料读取与个人草稿允许');const token=startNow?artifactId():undefined,preview=configured(data,startNow,token);if(preview.error)return setError(preview.error);
    let allowed=true;update(current=>{const fresh=configured(current,startNow,token);if(fresh.error){allowed=false;toast(fresh.error);return current;}return startNow?{...fresh.data,settings:{...fresh.data.settings,space:'我的空间'}}:fresh.data;});if(!allowed)return;if(startNow&&token){setTimeout(()=>update(current=>finishLocalGeneration(current,t.id,token,cost)),2400);toast('已按所选范围开始准备');go('task-progress');}else{toast('配置已保存，尚未允许助手准备');go('task-detail');}
  }
  return <div className="stack task-setup"><Card><h2>{t.title}</h2><p className="meta">工作{taskState(t)} · 个人草稿</p></Card>{!accepted(t)&&<Notice>先承接工作，再决定是否需要助手。</Notice>}<SectionTitle>准备什么</SectionTitle><SelectField label="产出方式" value={mode} options={OUTPUT_MODES} onChange={v=>{changed();setMode(v)}}/><SectionTitle>这次允许使用</SectionTitle>{t.sourceSession?<Card><Check label="任务引用的原话" value={includeSource} onChange={v=>{changed();setIncludeSource(v)}}/>{includeSource&&source&&<p className="task-source-preview">{source.text}</p>}<TaskSource task={t}/></Card>:<p className="meta">本人填写的任务要求</p>}{refs.length?<Card>{refs.map(m=>{const valid=!m.needsReview&&sourceAvailable(data,m)&&(!m.memoryId||data.memories.some(x=>x.id===m.memoryId&&!x.deleted&&x.confirmed&&!x.needsReview));return <div className="task-resource-choice" key={m.id}><Check label={m.title+(valid?'':' · 当前不可用')} value={ids.includes(m.id)} onChange={v=>{changed();if(v&&!valid)return toast('这份资料失效，先更新或移除');setIds(v?[...ids.filter(id=>id!==m.id),m.id]:ids.filter(id=>id!==m.id));}}/>{ids.includes(m.id)&&m.body&&valid&&<p className="meta">{m.body.slice(0,90)}</p>}{ids.includes(m.id)&&m.note&&valid&&<p className="meta">本人补充：{m.note}</p>}</div>})}</Card>:<Empty title="尚未附入资料" body="可按本人任务要求准备，或先补充资料" action="补充资料" onAction={()=>go('task-attachment')}/>}<Button tone="quiet" icon="paperclip" onClick={()=>go('task-attachment')}>管理附入资料</Button><div className="stat-grid"><Card><small className="meta">本次预计</small><h2>{cost}点</h2></Card><Card><small className="meta">已经使用</small><h2>{t.used??0}点</h2></Card></div><Field label="本任务额度上限" value={limit} onChange={v=>{changed();setLimit(v)}} type="number"/><p className="meta">保存到我的个人成果。额度与准备均为本地示例。</p><Check label="允许读取以上所选原话与资料" value={read} onChange={setRead}/><Check label="允许生成这次个人草稿" value={draft} onChange={setDraft}/>{error&&<p className="error-text">{error}</p>}<Button onClick={()=>save(true)}>{accepted(t)?'允许并开始准备':'先确认承接'}</Button><Button tone="secondary" onClick={()=>save(false)}>保存配置，稍后准备</Button><p className="meta">外部消息、邮件、共享与日程需在具体内容旁再次确认。</p></div>;
}
function Progress({task:t}:{task:TaskRecord}) {
  const {patch,go,start}=useTaskActions(t);const ready=t.aiStatus==='草稿完成',running=t.aiStatus==='准备中';
  return <div className="stack"><Card className="task-hero"><div className="section-title"><Badge>{t.aiStatus}</Badge><Icon name="sparkle"/></div><h2>{ready?'草稿准备好了':running?'正在准备个人草稿':t.aiStatus==='已暂停'?'当前准备已暂停':'继续这次准备'}</h2><p>{t.title}</p><p className="meta">实际工作仍为{taskState(t)}</p></Card><Card><Row title="产出方式" subtitle={taskOutputMode(t)} icon="file-text"/><Row title="允许的资料" subtitle={t.scope?.sources||'尚未确认范围'} icon="books"/><Row title="成果位置" subtitle="我的个人成果" icon="folder"/></Card>{t.failure&&<Notice tone="danger">{t.failure}</Notice>}{ready?<Button onClick={()=>go('task-result')}>查看并核对草稿</Button>:t.aiStatus==='失败'?<Button onClick={()=>go('task-failure')}>处理缺少的资料</Button>:<Button onClick={()=>t.authorized?start():go('task-plan')} disabled={running}>{running?'正在准备':t.authorized?'继续已允许的准备':'重新选择范围'}</Button>}{running&&<Button tone="secondary" icon="pause" onClick={()=>patch({aiStatus:'已暂停',generationToken:undefined,generationSnapshot:undefined},'暂停助手，保留已有成果')}>暂停准备</Button>}{!closed(t)&&<div className="action-grid"><Button tone="quiet" onClick={()=>{patch({aiStatus:'已停止',generationToken:undefined,generationSnapshot:undefined,authorized:false},'停止助手，工作责任保留');go('task-detail');}}>停止助手</Button><Button tone="quiet" onClick={()=>go('task-plan')}>调整准备范围</Button></div>}<Button tone="quiet" onClick={()=>go('task-detail')}>返回工作详情</Button></div>;
}
function Failure({task:t}:{task:TaskRecord}) {
  const {go,start,patch}=useTaskActions(t);return <div className="stack"><Notice tone="warning">{t.failure||'这次准备需要补齐资料'}</Notice><Card><h2>已有成果保留</h2><p className="meta">{artifacts(t).length}份成果</p><Row title="查看已有成果" icon="files" onClick={()=>go('task-result')}/><Row title="补充或替换资料" icon="paperclip" onClick={()=>go('task-attachment')}/><Row title="记录需要确认的问题" icon="chat-circle-text" onClick={()=>go('task-ask')}/></Card><Button onClick={()=>t.authorized?start(true):go('task-plan')}>{t.authorized?'仅重试未完成步骤':'重新确认范围并准备'}</Button><Button tone="secondary" onClick={()=>{patch({aiStatus:'已停止',generationToken:undefined,generationSnapshot:undefined,authorized:false},'停止未完成准备，保留已有成果');go('task-detail');}}>保留成果，停止准备</Button></div>;
}
function TaskMaterials({task:t}:{task:TaskRecord}) {
  const {go}=useTaskActions(t);const refs=t.materialRefs||[],qs=inquiries(t);return <div className="stack"><SectionTitle action="补充" onAction={()=>go('task-attachment')}>附入资料</SectionTitle>{refs.length?<Card>{refs.map(m=><Row key={m.id} title={m.title} subtitle={m.needsReview?'来源待核对':m.body?.slice(0,76)||'已关联资料'} icon="paperclip" onClick={()=>go('task-attachment')}/>)}</Card>:<Empty title="还没有附入资料" body="手工行动可以直接推进，需要时再补充资料" action="补充资料" onAction={()=>go('task-attachment')}/>}<TaskSource task={t}/><SectionTitle action="管理" onAction={()=>go('task-ask')}>问题与答复</SectionTitle>{qs.length?<Card>{qs.map(q=><Row key={q.id} title={q.question} subtitle={q.answer||q.nextFollowUp&&`${dueText(q.nextFollowUp)}跟进`||'尚未记录答复'} badge={q.status} icon="chat-circle-text" onClick={()=>go('task-ask')}/>)}</Card>:<p className="meta">没有待确认问题</p>}</div>;
}
function Result({task:t,embedded=false}:{task:TaskRecord;embedded?:boolean}) {
  const {data,update,navigate,toast}=useOops(),{go,patch}=useTaskActions(t);const list=artifacts(t),latest=latestArtifacts(t),[selected,setSelected]=useViewState<string[]>(deliveryKey(data.settings.space,t),t.deliveryArtifactIds||latest.map(a=>a.id)),[create,setCreate]=useState(false);const ownKey=`task-manual-artifact:${data.settings.space}:${t.id}`;const [ownTitle,setOwnTitle]=useViewState(ownKey+':title',''),[ownBody,setOwnBody]=useViewState(ownKey+':body',''),[ownKind,setOwnKind]=useViewState(ownKey+':kind','文档'),[ownReviewed,setOwnReviewed]=useViewState(ownKey+':reviewed',false);
  function saveOwn(){if(!taskBelongsToMe(data,t)||closed(t))return toast('请由当前负责人保存交付物');if(!ownTitle.trim()||!ownBody.trim())return toast('填写成果标题与正文');if(!taskSourceAvailable(data,t))return toast('先核对当前任务来源与资料');const version=Math.max(t.version,...list.map(a=>a.version),0)+1,next:Artifact={id:artifactId(),kind:ownKind as Artifact['kind'],title:ownTitle.trim(),body:ownBody.trim().split('\n\n'),version,created:stamp(),needsReview:!ownReviewed,sourceNeedsReview:false,reviewedAt:ownReviewed?stamp():undefined,sourceSession:t.sourceSession,sourceId:t.sourceId,sourceTime:t.sourceTime,sources:t.sources},all=[...list,next];patch({artifacts:all,version,needsReview:latestTaskArtifacts({...t,artifacts:all}).some(a=>a.needsReview||!a.reviewedAt),deliveryArtifactIds:undefined,authorized:false,generationToken:undefined,generationSnapshot:undefined,aiStatus:t.aiStatus==='准备中'?'已停止':t.aiStatus},`本人保存${next.kind} v${version}`);setOwnTitle('');setOwnBody('');setOwnReviewed(false);setCreate(false);toast('本人交付物已保存');}
  function submit(){if(!taskBelongsToMe(data,t)||closed(t))return toast('请由当前负责人提交这项工作');if(!accepted(t))return go('task-accept');if(!taskSourceAvailable(data,t))return go('task-edit');const chosen=latest.filter(a=>selected.includes(a.id));if(!chosen.length)return toast('选择本次交付的成果版本');if(!chosen.every(a=>!a.sourceNeedsReview&&!a.needsReview&&!!a.reviewedAt&&sourceAvailable(data,a)&&provenanceAvailable(data,a.sources)))return toast('先核对所选成果的正文与来源');patch({status:'待验收',deliveryArtifactIds:chosen.map(a=>a.id)},`明确提交交付版本：${chosen.map(a=>`${a.title} v${a.version}`).join('、')}`);go('task-complete','交付验收');}
  function returnToSession(){const sid=t.relatedSessionId||t.sourceSession,session=data.sessions.find(s=>s.id===sid),result=latest.find(a=>a.kind==='资料');if(!session||!visibleSession(data,session.id))return toast('关联会话当前不可见');if(!result)return toast('先选择一份资料成果');if(result.sourceNeedsReview||result.needsReview||!result.reviewedAt||!taskSourceAvailable(data,t)||!sourceAvailable(data,result)||!provenanceAvailable(data,result.sources))return toast('先核对这份成果与当前来源');const id=`material-${t.id}-${result.id}`,name=`${result.title} · v${result.version}`,visibility=data.settings.space==='我的空间'?'私有' as const:'项目共享' as const;update(current=>({...current,sessions:current.sessions.map(s=>s.id===session.id?{...s,attachments:[...new Set([...s.attachments,name])]}:s),memories:current.memories.some(m=>m.id===id)?current.memories.map(m=>m.id===id?{...m,body:result.body.join('\n'),visibility,deleted:false}:m):[...current.memories,{id,title:name,body:result.body.join('\n'),category:'收藏' as const,tags:['资料','任务成果',t.id],visibility,confirmed:true,updated:'今天',sourceSession:session.id,...(t.sourceSession===session.id?{sourceId:t.sourceId,sourceTime:t.sourceTime}:{}),sources:[makeSourceReference(current,{kind:'task',id:t.id,version:t.version})]}],settings:visibility==='项目共享'?{...current.settings,retention:{...current.settings.retention,['memory-space:'+id]:current.settings.space}}:current.settings}));toast('资料已附回本会话');navigate({view:'session-detail',id:session.id,mode:'资料'});}
  return <div className="stack">{!embedded&&<div><h1 className="title">成果</h1><p className="meta">{t.title}</p></div>}{t.status==='已完成'&&t.completion&&<Card><SectionTitle>实际完成结果</SectionTitle><p className="task-body">{t.completion.summary}</p>{t.completion.remaining&&<p className="meta">后续：{t.completion.remaining}</p>}</Card>}{t.sourceNeedsReview&&<Notice tone="warning">来源已变化，旧稿保留，需先核对要求。</Notice>}{list.length?<>{latest.map(a=><Card key={a.id} className="task-artifact-card"><div className="section-title"><Badge tone="gray">{a.kind} · v{a.version}</Badge><Badge>{artifactLabel(a)}</Badge></div><h3>{a.title}</h3><p className="task-artifact-excerpt">{a.body[0]||'尚无正文'}</p><Row title="打开这份成果" subtitle={a.created} icon="arrow-up-right" onClick={()=>go('task-preview',a.id)}/>{taskBelongsToMe(data,t)&&taskWorkKind(t)==='交付'&&!closed(t)&&<Check label="纳入本次交付" value={selected.includes(a.id)} onChange={v=>setSelected(v?[...selected.filter(id=>id!==a.id),a.id]:selected.filter(id=>id!==a.id))}/>}</Card>)}{taskBelongsToMe(data,t)&&latest.some(a=>a.needsReview||!a.reviewedAt)&&<Button onClick={()=>go('task-complete','草稿核对')}>核对所选草稿</Button>}{taskBelongsToMe(data,t)&&taskWorkKind(t)==='交付'&&!closed(t)&&<Button tone={latest.some(a=>a.needsReview||!a.reviewedAt)?'secondary':'primary'} onClick={submit}>提交选定成果验收</Button>}<Button tone="quiet" icon="clock-counter-clockwise" onClick={()=>go('task-versions')}>比较历史版本</Button></>:!t.completion&&<Empty title="没有交付物也可以推进工作" body={taskWorkKind(t)==='行动'?'记录实际结果即可完成，助手准备可选':'补充一份交付物，或让助手准备草稿'} action={taskWorkKind(t)==='行动'?'记录实际结果':'准备交付草稿'} onAction={()=>go(taskWorkKind(t)==='行动'?'task-complete':'task-plan',taskWorkKind(t)==='行动'?'人工完成':undefined)}/>}{taskBelongsToMe(data,t)&&!closed(t)&&<Button tone="secondary" icon="plus" onClick={()=>setCreate(true)}>保存本人交付物</Button>}<SectionTitle action="起草" onAction={()=>go('task-send')}>需要沟通时</SectionTitle><Card><Row title="起草跟进消息" subtitle="对象和正文由你确认" icon="chat-circle-text" onClick={()=>go('task-send')}/>{latest.length>0&&<Row title="请人审阅选定成果" icon="envelope-simple" onClick={()=>go('task-email')}/>}</Card>{latest.some(a=>a.kind==='资料')&&<Button tone="secondary" onClick={returnToSession}>带回本会话资料</Button>}<Sheet open={create} onClose={()=>setCreate(false)} title="保存本人交付物"><div className="stack"><Field label="成果标题" value={ownTitle} onChange={v=>{setOwnTitle(v);setOwnReviewed(false)}}/><SelectField label="成果类型" value={ownKind} onChange={setOwnKind} options={['文档','资料','PPT']}/><Field label={ownKind==='PPT'?'每页正文（空行分页）':'正文'} value={ownBody} onChange={v=>{setOwnBody(v);setOwnReviewed(false)}} multiline/><Check label="已核对这份正文与当前来源" value={ownReviewed} onChange={setOwnReviewed}/><Button onClick={saveOwn}>保存这份成果</Button></div></Sheet></div>;
}
function diffLines(left:string[],right:string[]) {
  const a=left.join('\n').split('\n'),b=right.join('\n').split('\n');if(a.length*b.length>500000)return [...a.map(text=>({kind:'删除',text})),...b.map(text=>({kind:'新增',text}))];
  const grid=Array.from({length:a.length+1},()=>new Uint32Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)grid[i][j]=a[i]===b[j]?grid[i+1][j+1]+1:Math.max(grid[i+1][j],grid[i][j+1]);
  const rows:{kind:string;text:string}[]=[];let i=0,j=0;while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){rows.push({kind:'保留',text:a[i]});i++;j++;}else if(j<b.length&&(i===a.length||grid[i][j+1]>=grid[i+1][j])){rows.push({kind:'新增',text:b[j++]});}else rows.push({kind:'删除',text:a[i++]});}return rows;
}
function Versions({task:t}:{task:TaskRecord}) {
  const {data}=useOops(),{go}=useTaskActions(t),all=artifacts(t),latest=all[all.length-1],previous=all.slice(0,-1).reverse().find(a=>a.kind===latest?.kind)||all[0],key=`task-compare:${data.settings.space}:${t.id}`;const [leftId,setLeft]=useViewState(key+':left',previous?.id||''),[rightId,setRight]=useViewState(key+':right',latest?.id||''),left=all.find(a=>a.id===leftId),right=all.find(a=>a.id===rightId),labels=all.map(a=>`${a.title} · v${a.version} · ${a.id.slice(-8)}`),rows=left&&right?diffLines(left.body,right.body):[];
  return <div className="stack">{all.length?<><SelectField label="比较前的版本" value={left?labels[all.indexOf(left)]:'选择一个版本'} options={['选择一个版本',...labels]} onChange={v=>setLeft(all[labels.indexOf(v)]?.id||'')}/><SelectField label="比较后的版本" value={right?labels[all.indexOf(right)]:'选择一个版本'} options={['选择一个版本',...labels]} onChange={v=>setRight(all[labels.indexOf(v)]?.id||'')}/>{left&&right&&left.id!==right.id?<><p className="meta">新增 {rows.filter(r=>r.kind==='新增').length}行 · 删除 {rows.filter(r=>r.kind==='删除').length}行</p><Card className="task-diff">{left.title!==right.title&&<p className="task-diff-title">标题：{left.title} → {right.title}</p>}{rows.map((r,i)=><p className={`task-diff-line ${r.kind==='新增'?'added':r.kind==='删除'?'removed':'unchanged'}`} key={i}><span className="task-diff-marker">{r.kind==='新增'?'+':r.kind==='删除'?'−':' '}</span><span>{r.text||' '}</span></p>)}</Card><div className="action-grid"><Button tone="secondary" onClick={()=>go('task-preview',left.id)}>打开旧版</Button><Button onClick={()=>go('task-preview',right.id)}>打开新版</Button></div></>:<Notice>选择两个不同版本，即可查看正文改动。</Notice>}<SectionTitle>全部版本</SectionTitle><Card>{[...all].reverse().map(a=><Row key={a.id} title={a.title} subtitle={`${a.kind} · v${a.version} · ${artifactLabel(a)}`} icon="clock-counter-clockwise" onClick={()=>go('task-preview',a.id)}/>)}</Card></>:<Empty title="还没有版本" body="保存第一份成果后，在这里比较正文改动" action="返回成果" onAction={()=>go('task-result')}/>}</div>;
}
function Preview({task:t,edit=false}:{task:TaskRecord;edit?:boolean}) {
  const {data,route,toast}=useOops(),{patch,go}=useTaskActions(t),all=artifacts(t);const [selectedId,setSelectedId]=useViewState(`task-selected-artifact:${data.settings.space}:${t.id}`,route.mode||latestArtifacts(t)[0]?.id||'');const id=route.mode||selectedId,a=all.find(x=>x.id===id),key=`task-artifact:${data.settings.space}:${t.id}:${id}`;const [page,setPage]=useViewState(key+':page',0),[body,setBody]=useViewState<string[]>(key+':body',a?.body||[]),[title,setTitle]=useViewState(key+':title',a?.title||''),[rechecked,setRechecked]=useViewState(`${key}:rechecked:${t.version}:${JSON.stringify([t.sourceSession,t.sourceId,t.sourceTime,t.sources])}`,false);useEffect(()=>{if(route.mode)setSelectedId(route.mode)},[route.mode,setSelectedId]);const shown=edit?body:a?.body||[],valid=!!a&&!a.sourceNeedsReview&&sourceAvailable(data,a)&&provenanceAvailable(data,a.sources),labels=all.map(x=>`${x.title} · v${x.version} · ${x.id.slice(-8)}`);
  const [backup,setBackup]=useState<'copy'|'download'|null>(null);
  if(!a)return <Empty title="没有找到这个版本" body="选择已保存的成果，打开的正文不会自动换成新版" action="返回成果" onAction={()=>go('task-result')}/>;
  const exportAccess=taskArtifactExportAccess(data,t,a);
  function save(){if(!title.trim()||!body.length||body.some(s=>!s.trim()))return toast('填写标题与完整正文');if(!taskSourceAvailable(data,t))return toast('先核对当前任务来源与资料');if(!valid&&!rechecked)return toast('旧来源已变化，需重新核对正文');const version=Math.max(t.version,...all.map(x=>x.version))+1,next:Artifact={...a!,id:artifactId(),title:title.trim(),body,version,created:stamp(),reviewedAt:undefined,reviewHistory:undefined,needsReview:true,sourceNeedsReview:false,...(!valid?{sourceSession:t.sourceSession,sourceId:t.sourceId,sourceTime:t.sourceTime,sources:t.sources}:{})};patch({...archiveTaskCompletion(t),artifacts:[...all,next],version,needsReview:true,deliveryArtifactIds:undefined,authorized:false,generationToken:undefined,generationSnapshot:undefined,generationSources:undefined,generationSpace:undefined,aiStatus:t.aiStatus==='准备中'?'已停止':t.aiStatus,status:t.status==='已完成'?'已承接':t.status==='待验收'?'进行中':t.status},`另存${a!.kind}新版本v${version}`);go('task-preview',next.id);}
  function exportArtifact(action:'copy'|'download',historyConfirmed=false){const access=taskArtifactExportAccess(data,t,a!);if(access.mode==='blocked')return toast(access.error!);if(access.mode==='history'&&!historyConfirmed){setBackup(action);return;}const historical=historyConfirmed||access.mode==='history',text=(historical?'历史备份\n此为保存的旧版正文，不能作为当前有效成果或本次交付依据。\n\n':'')+a!.title+' · v'+a!.version+'\n\n'+a!.body.join('\n\n');setBackup(null);if(action==='copy'){if(!navigator.clipboard)return toast('当前环境不允许复制');navigator.clipboard.writeText(text).then(()=>toast(historical?'已复制历史备份':'已复制这版正文')).catch(()=>toast('当前环境不允许复制'));return;}const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=(historical?'历史备份-':'')+a!.title+'-v'+a!.version+'.txt';link.click();URL.revokeObjectURL(url);toast(historical?'历史备份已下载':'这版文本已下载');}
  function copy(){exportArtifact('copy');}
  function download(){exportArtifact('download');}
  return <div className="stack"><div className="section-title"><Badge>{a.kind}</Badge><Badge tone="gray">v{a.version} · {artifactLabel(a)}</Badge></div>{!edit&&<SelectField label="正在阅读的版本" value={labels[all.indexOf(a)]} options={labels} onChange={v=>{const chosen=all[labels.indexOf(v)];if(chosen){setSelectedId(chosen.id);go('task-preview',chosen.id)}}}/>} {!valid&&<Notice tone="warning">旧版来源已变化，保留正文供查看，不能直接重新交付。</Notice>}{a.kind==='PPT'&&<Chips items={shown.map((_,i)=>`第${i+1}页`)} value={`第${Math.min(page,shown.length-1)+1}页`} onChange={s=>setPage(Number(s.replace(/\D/g,''))-1)}/>} {edit?<><Field label="成果标题" value={title} onChange={v=>{setTitle(v);setRechecked(false)}}/><Field label={a.kind==='PPT'?'当前页正文':'正文'} value={a.kind==='PPT'?body[Math.min(page,body.length-1)]||'':body.join('\n\n')} onChange={s=>{setRechecked(false);setBody(a.kind==='PPT'?body.map((x,i)=>i===Math.min(page,body.length-1)?s:x):s.split('\n\n'))}} multiline/>{!valid&&<Check label="已用当前有效资料重新核对这份正文" value={rechecked} onChange={setRechecked}/>}<Button onClick={save}>另存新版本</Button><Button tone="quiet" onClick={()=>go('task-preview',a.id)}>返回这份原稿</Button></>:<><Card className={a.kind==='PPT'?'presentation-card':'document-card'}><p className="meta">{a.kind==='PPT'?`${Math.min(page,shown.length-1)+1} / ${shown.length}`:a.created}</p><h2>{a.title}</h2>{(a.kind==='PPT'?[shown[Math.min(page,shown.length-1)]]:shown).map((p,i)=><p key={i} className="task-body">{p}</p>)}</Card>{taskBelongsToMe(data,t)&&<Button onClick={()=>go('task-artifact-edit',a.id)}>编辑并另存</Button>}{taskBelongsToMe(data,t)&&!closed(t)&&<Button tone="secondary" onClick={()=>go('task-complete','草稿核对')}>核对成果正文</Button>}{exportAccess.mode==='blocked'&&<Notice tone="warning">{exportAccess.error}</Notice>}<div className="action-grid"><Button tone="quiet" icon="copy" onClick={copy} disabled={exportAccess.mode==='blocked'}>{exportAccess.mode==='history'?'复制历史备份':'复制正文'}</Button><Button tone="quiet" icon="download-simple" onClick={download} disabled={exportAccess.mode==='blocked'}>{exportAccess.mode==='history'?'下载历史备份':'下载这版文本'}</Button></div><Button tone="quiet" onClick={()=>go('task-email',a.id)}>用选定成果起草审阅邮件</Button></>}<TaskSource task={t}/><Sheet open={!!backup} onClose={()=>setBackup(null)} title="备份历史正文"><div className="stack"><p>这份旧稿的来源或要求已经变化。备份会保留原正文并标明历史，不能作为当前有效成果或本次交付依据。</p><Button onClick={()=>backup&&exportArtifact(backup,true)}>确认{backup==='copy'?'复制':'下载'}历史备份</Button><Button tone="quiet" onClick={()=>setBackup(null)}>继续查看旧稿</Button></div></Sheet></div>;
}
function History({task:t}:{task:TaskRecord}) {
  const {go}=useTaskActions(t);return <div className="stack"><SectionTitle>工作记录</SectionTitle>{t.activities.length?<Card><div className="timeline">{[...t.activities].reverse().map((s,i)=><div key={i} className="timeline-item"><Icon name="clock" size={18}/><p>{s}</p></div>)}</div></Card>:<p className="meta">还没有推进记录</p>}{!!t.completionHistory?.length&&<><SectionTitle>历史完成结果</SectionTitle>{[...t.completionHistory].reverse().map(result=><Card key={result.id}><Badge tone="gray">历史记录</Badge><p className="task-body">{result.summary}</p><p className="meta">{result.completedAt} · {result.kind}</p>{result.remaining&&<p className="meta">当时的后续：{result.remaining}</p>}</Card>)}</>}<Row title="查看沟通与日程模拟回执" icon="paper-plane-tilt" onClick={()=>go('task-receipt')}/></div>;
}
function Receipts({task:t}:{task:TaskRecord}) {
  const {data,route}=useOops(),{go}=useTaskActions(t),list=data.receipts.filter(r=>r.taskId===t.id&&(r.space||'我的空间')===data.settings.space&&['我',data.settings.name].includes(r.actor||'我')),selected=list.find(r=>r.id===route.mode),shown=selected?[selected]:[...list].reverse();return <div className="stack"><p className="meta">本地模拟回执，没有真实发送或日历写入。</p>{shown.length?shown.map(r=><Card key={r.id}><div className="section-title"><Badge>{r.kind}</Badge><Badge tone="gray">模拟完成</Badge></div><h3>{r.target}</h3><p className="task-body">{r.body}</p><p className="meta">{r.date}</p></Card>):<Empty title="还没有操作回执" body="确认具体沟通内容后，模拟记录保存在这里"/>}<Button tone="secondary" onClick={()=>go('task-detail')}>返回这项工作</Button></div>;
}
function Complete({task:t}:{task:TaskRecord}) {
  const {data,route,toast}=useOops(),{go,apply}=useTaskActions(t);const manual=taskWorkKind(t)==='行动'&&route.mode!=='草稿核对',review=route.mode==='草稿核对',all=artifacts(t),latest=latestArtifacts(t),key=`task-complete:${data.settings.space}:${t.id}:${t.version}:${route.mode||''}`;
  const [ids,setIds]=useViewState<string[]>(deliveryKey(data.settings.space,t),t.deliveryArtifactIds||latest.map(a=>a.id)),[checks,setChecks]=useViewState<Record<string,boolean>>(key+':criteria',{}),[versions,setVersions]=useViewState<Record<string,boolean>>(key+':versions',{}),[summary,setSummary]=useViewState(key+':summary',t.status==='已完成'?t.completion?.summary||'':''),[remaining,setRemaining]=useViewState(key+':remaining',t.status==='已完成'?t.completion?.remaining||'':''),[confirmed,setConfirmed]=useViewState(key+':confirmed',false),[error,setError]=useState('');const selected=all.filter(a=>ids.includes(a.id)),criteria=t.criteria||[];
  function finish(){
    if(!taskSourceAvailable(data,t))return setError('先重新核对来源与当前资料');if(manual){if(!confirmed)return setError('确认实际工作已完成');if(criteria.some(c=>!checks[c]))return setError('逐项核对完成标准');if(apply(current=>createManualCompletion(current,t.id,{summary,remaining}), '实际结果已保存，工作已完成'))go('task-detail');return;}
    if(!selected.length)return setError('选择本次核对的成果版本');if(!selected.every(a=>versions[a.id]))return setError('打开并核对所选成果正文');if(!review&&criteria.some(c=>!checks[c]))return setError('逐项核对交付标准');if(!review&&!confirmed)return setError('确认本次工作已实际交付');const helper=review?(current:AppData)=>taskReviewArtifacts(current,t.id,selected.map(a=>a.id)):(current:AppData)=>createDeliveryCompletion(current,t.id,{artifactIds:selected.map(a=>a.id),summary,remaining});if(apply(helper,review?'所选草稿已核对，工作尚未完成':'选定交付版本已验收'))go(review?'task-result':'task-detail');
  }
  return <div className="stack"><Card><Badge>{manual?'实际工作结果':review?'草稿核对':'交付验收'}</Badge><h2>{t.title}</h2><p className="meta">{taskState(t)}</p></Card>{!manual&&<><SectionTitle>{review?'选择核对的草稿':'本次交付的版本'}</SectionTitle>{latest.length?latest.map(a=><Card key={a.id}><Check label={`${a.title} · v${a.version}`} value={ids.includes(a.id)} onChange={v=>setIds(v?[...ids.filter(id=>id!==a.id),a.id]:ids.filter(id=>id!==a.id))}/>{ids.includes(a.id)&&<><Row title="打开正文" subtitle={`${a.kind} · ${artifactLabel(a)}`} icon="files" onClick={()=>go('task-preview',a.id)}/><Check label="已读正文并核对依据" value={!!versions[a.id]} onChange={v=>setVersions(x=>({...x,[a.id]:v}))}/></>}</Card>):<Empty title="还没有交付物" body="上传或保存一份成果，再核对交付版本" action="准备草稿" onAction={()=>go('task-plan')}/>}</>}{!review&&<><Field label={manual?'实际完成了什么？':'交付说明'} value={summary} onChange={setSummary} multiline placeholder={manual?'记录真实结果，或已完成的具体事项':'说明这次交付的范围与结果'}/><Field label="后续事项（可留空）" value={remaining} onChange={setRemaining} multiline/>{criteria.length>0&&<><SectionTitle>完成标准</SectionTitle>{criteria.map(c=><Check key={c} label={c} value={!!checks[c]} onChange={v=>setChecks(x=>({...x,[c]:v}))}/>)}</>}<Check label={manual?'确认实际工作已完成':'确认选定成果已经实际交付'} value={confirmed} onChange={setConfirmed}/></>}{error&&<p className="error-text">{error}</p>}<Button onClick={finish} disabled={t.status==='已拒绝'||t.status==='已取消'}>{manual?'保存结果并完成':review?'确认已核对草稿':'验收选定交付版本'}</Button><Button tone="secondary" onClick={()=>go('task-detail')}>稍后继续</Button>{review&&<p className="meta">核对草稿只确认内容，不代表实际工作已经完成。</p>}</div>;
}
function InquiryEditor({task:t,inquiry:q,onClose}:{task:TaskRecord;inquiry:TaskInquiry;onClose:()=>void}) {
  const {data,update,toast}=useOops(),{patch,go,apply}=useTaskActions(t),key=`task-inquiry:${data.settings.space}:${t.id}:${q.id}`;const [question,setQuestion]=useViewState(key+':question',q.question),[answer,setAnswer]=useViewState(key+':answer',q.answer||''),[target,setTarget]=useViewState(key+':target',q.target||''),[follow,setFollow]=useViewState(key+':follow',q.nextFollowUp||''),[error,setError]=useState(''),[replace,setReplace]=useState(false);
  function save(status:TaskInquiry['status']) { if(follow.trim()&&validMoment(follow)===undefined){setError('填写有效跟进时间');return false;}return apply(current=>setInquiry(current,t.id,{...q,question:question.trim(),answer:answer.trim(),target:target.trim(),nextFollowUp:normalizeMoment(follow),status}),status==='已解决'?'答复已核对，问题已解决':status==='已回答'?'答复已记录，等待核对':'跟进已保存'); }
  function compose(){if(follow.trim()&&validMoment(follow)===undefined)return setError('填写有效跟进时间');const inquiry:TaskInquiry={...q,question:question.trim(),answer:answer.trim(),target:target.trim(),nextFollowUp:normalizeMoment(follow),status:q.status==='已解决'&&question.trim()===q.question&&answer.trim()===(q.answer||'')?'已解决':answer.trim()?'已回答':'待回答'},preview=setInquiry(data,t.id,inquiry);if(preview.error)return setError(preview.error);let failed=false;update(current=>{const saved=setInquiry(current,t.id,inquiry);if(saved.error){failed=true;toast(saved.error);return current;}const actual=saved.data.tasks.find(x=>x.id===t.id);if(!actual){failed=true;toast('工作已移除');return current;}const draft=initialDraft(actual,'邮件',saved.data.settings.name,[],{data:saved.data,space:saved.data.settings.space,replyToInquiryId:q.id});return saveCommunicationDraft(saved.data,t.id,draft,'邮件',true,actual.drafts?.['邮件']);});if(failed)return;onClose();go('task-email',q.id);}
  return <div className="stack"><Badge tone="gray">{q.status}</Badge><Field label="需要确认的问题" value={question} onChange={setQuestion} multiline/><Field label="询问或跟进对象（可留空）" value={target} onChange={setTarget}/><Field label="收到的答复" value={answer} onChange={setAnswer} multiline placeholder="记录实际答复，不自动假定问题已解决"/><Field label="下一次跟进（可留空）" value={follow} onChange={setFollow} placeholder="2026-10-09 10:00" hint="按当前设备本地时间"/>{error&&<p className="error-text">{error}</p>}<Button onClick={()=>{if(save(answer.trim()?'已回答':'待回答'))onClose()}}>保存答复与跟进</Button>{answer.trim()&&<Button tone="secondary" onClick={()=>{if(save('已解决'))onClose()}}>核对答复，确认已解决</Button>}<Button tone="quiet" onClick={()=>save('待回答')}>继续等待，保留跟进</Button><Button tone="quiet" icon="envelope-simple" onClick={()=>t.drafts?.['邮件']?setReplace(true):compose()}>为这个问题起草询问</Button>{taskBelongsToMe(data,t)&&q.status==='已解决'&&q.answer&&<Button tone="secondary" icon="paperclip" onClick={()=>{const title=`答复：${q.question}`,id=`inquiry-material:${q.id}`,refs=[...(t.materialRefs||[]).filter(m=>m.id!==id),{id,title,body:q.answer}];patch({materialRefs:refs,materials:[...new Set([...(t.materials||[]),title])],authorized:false,generationToken:undefined,generationSnapshot:undefined,aiStatus:t.aiStatus==='准备中'?'已停止':t.aiStatus},'本人将已核对问题答复附为任务资料');toast('已确认答复附入资料');onClose();}}>将已解决答复附入资料</Button>}<Sheet open={replace} onClose={()=>setReplace(false)} title="保留原邮件草稿？"><div className="stack"><p>这项任务已有邮件草稿。新询问将替换当前草稿。</p><Button onClick={()=>{setReplace(false);compose()}}>使用这次询问内容</Button><Button tone="secondary" onClick={()=>{setReplace(false);onClose();go('task-email')}}>打开原草稿</Button></div></Sheet></div>;
}
function Questions({task:t}:{task:TaskRecord}) {
  const {data}=useOops(),{apply}=useTaskActions(t),key=`task-questions:${data.settings.space}:${t.id}`;const [text,setText]=useViewState(key+':text',''),[target,setTarget]=useViewState(key+':target',['我',data.settings.name].includes(t.requester)?'':t.requester),[follow,setFollow]=useViewState(key+':follow',''),[selected,setSelected]=useState<string|null>(null),[newOpen,setNewOpen]=useState(false),[filter,setFilter]=useViewState(key+':filter','未解决'),[error,setError]=useState('');const all=inquiries(t),list=all.filter(q=>filter==='全部'||filter==='已解决'?filter==='全部'||q.status==='已解决':q.status!=='已解决'),active=all.find(q=>q.id===selected);
  function add(){if(!text.trim())return setError('填写具体问题');if(follow.trim()&&validMoment(follow)===undefined)return setError('填写有效跟进时间');if(apply(current=>setInquiry(current,t.id,{id:artifactId(),question:text.trim(),target:target.trim(),nextFollowUp:normalizeMoment(follow),status:'待回答',created:stamp()}),'问题已记录')){setText('');setNewOpen(false);}}
  return <div className="stack"><div className="section-title"><h2>问题与跟进</h2><Button tone="quiet" icon="plus" onClick={()=>setNewOpen(true)}>新增</Button></div><Chips items={['未解决','已解决','全部']} value={filter} onChange={setFilter}/>{list.length?<Card>{list.map(q=><Row key={q.id} title={q.question} subtitle={q.answer||q.nextFollowUp&&`${dueText(q.nextFollowUp)}跟进`||q.target&&`等待${q.target}答复`||'尚未记录答复'} badge={q.status} icon="chat-circle-text" onClick={()=>setSelected(q.id)}/>)}</Card>:<Empty title={filter==='已解决'?'还没有已解决问题':'没有待确认问题'} body="需要时记录缺口、收到的答复与跟进时间" action="记录问题" onAction={()=>setNewOpen(true)}/>}<Sheet open={newOpen} onClose={()=>setNewOpen(false)} title="记录问题"><div className="stack"><Field label="需要确认什么？" value={text} onChange={setText} multiline/><Field label="跟进对象（可留空）" value={target} onChange={setTarget}/><Field label="下一次跟进（可留空）" value={follow} onChange={setFollow} placeholder="2026-10-09 10:00" hint="按当前设备本地时间"/>{error&&<p className="error-text">{error}</p>}<Button onClick={add}>保存问题</Button><p className="meta">先保存在工作中，需要询问时再起草消息。</p></div></Sheet><Sheet open={!!active} onClose={()=>setSelected(null)} title="问题详情">{active&&<InquiryEditor key={active.id} task={t} inquiry={active} onClose={()=>setSelected(null)}/>}</Sheet></div>;
}
export function availableTaskMaterials(data:AppData):TaskMaterial[] {
  return data.sessions.filter(session=>visibleSession(data,session.id)).flatMap(session=>session.attachments.filter(title=>materialVisible(data,session.id,title)).map(title=>{const memory=data.memories.find(m=>m.sourceSession===session.id&&m.title===title&&!m.deleted&&m.confirmed&&!m.needsReview&&!m.tags.includes('待复核'));return {id:`attachment:${session.id}:${encodeURIComponent(title)}`,title,memoryId:memory?.id,body:memory?.body,sourceSession:session.id,sourceId:memory?.sourceId,sourceTime:memory?.sourceTime};}));
}
function Supplement({task:t}:{task:TaskRecord}) {
  const {data,toast}=useOops(),{patch,go}=useTaskActions(t),key=`task-supplement:${data.settings.space}:${t.id}`;const [text,setText]=useViewState(key+':text',''),[choice,setChoice]=useViewState(key+':choice',''),[name,setName]=useViewState(key+':name',''),[error,setError]=useState(''),options=availableTaskMaterials(data),label=(m:TaskMaterial)=>`${m.title} · ${data.sessions.find(s=>s.id===m.sourceSession)?.title||'本人补充'} · ${m.id.slice(-12)}`,labels=options.map(label),selected=options.find(m=>m.id===choice);
  function changeMaterials(refs:TaskMaterial[],activity:string){patch({...archiveTaskCompletion(t),materialRefs:refs,materials:refs.map(m=>m.title),version:t.version+1,needsReview:artifacts(t).length>0,deliveryArtifactIds:undefined,artifacts:artifacts(t).map(a=>({...a,needsReview:true})),authorized:false,generationToken:undefined,generationSnapshot:undefined,aiStatus:t.aiStatus==='未启动'?'未启动':'待授权',failure:undefined,status:t.status==='已完成'?'已承接':t.status=== '待验收'?'进行中':t.status},activity);}
  function save(){if(!selected&&!text.trim())return setError('选择一份当前资料，或填写本人补充内容');if(selected&&!materialVisible(data,selected.sourceSession!,selected.title))return setError('这份资料的访问范围已变化');const material:TaskMaterial=selected?{...selected,note:text.trim()||undefined}:{id:`manual:${artifactId()}`,title:name.trim()||text.trim().slice(0,35),body:text.trim()};changeMaterials([...(t.materialRefs||[]).filter(m=>m.id!==material.id),material],`附入资料：${material.title}，旧成果待核对`);setText('');setName('');setChoice('');toast('资料已附入当前任务');go(t.sourceNeedsReview?'task-edit':'task-detail');}
  return <div className="stack"><SelectField label="选择当前可见资料" value={selected?label(selected):'不选已有资料'} options={['不选已有资料',...labels]} onChange={v=>setChoice(options[labels.indexOf(v)]?.id||'')}/>{!selected&&<Field label="资料名称（可留空）" value={name} onChange={setName}/>}<Field label={selected?'补充说明（可留空）':'本人补充内容'} value={text} onChange={setText} multiline/>{error&&<p className="error-text">{error}</p>}<Button onClick={save}>附入这项工作</Button>{(t.materialRefs||[]).length>0&&<><SectionTitle>已附入的资料</SectionTitle>{t.materialRefs?.map(m=><Card key={m.id}><Badge tone="gray">{m.needsReview?'待核对':'已附入'}</Badge><h3>{m.title}</h3>{m.body&&<p className="task-body">{m.body}</p>}{m.note&&<p className="task-body">本人补充：{m.note}</p>}<Button tone="quiet" onClick={()=>{changeMaterials((t.materialRefs||[]).filter(x=>x.id!==m.id),`移除资料：${m.title}，撤回旧准备授权`);toast('已移除，旧成果保留待核对')}}>从当前任务移除</Button></Card>)}</>}</div>;
}
export default function Tasks() {
  const {data,route,navigate}=useOops();if(route.view==='tasks')return <TaskList/>;if((route.view==='task-edit'&&!route.id)||route.view==='task-create')return <Requirements key="new"/>;
  const t=data.tasks.find(x=>x.id===route.id) as TaskRecord|undefined;if(!t)return <Empty title="没有找到这项工作" body="返回列表查看当前工作" action="返回任务" onAction={()=>navigate({view:'tasks'})}/>;if(!taskVisible(data,t))return <Empty title="这项工作不在当前空间" body="切回个人空间，或查看当前团队已共享的工作" action="返回当前列表" onAction={()=>navigate({view:'tasks'})} icon="lock-key"/>;
  const ownerRoutes=['task-accept','task-reject','task-transfer','task-transfer-response','task-edit','task-change','task-plan','task-authorize','task-budget','task-progress','task-failure','task-artifact-edit','task-complete','task-attachment','task-progress-note'];if(ownerRoutes.includes(route.view)&&!taskBelongsToMe(data,t))return <Empty title="这项工作由对方负责" body="可以查看成果与记录，或继续跟进问题" action="查看跟进" onAction={()=>navigate({view:'task-ask',id:t.id})}/>;
  const key=`${route.view}:${t.id}:${route.mode||''}`;
  switch(route.view){
    case 'task-detail':return <Detail key={key} task={t}/>;
    case 'task-accept':return <Accept key={key} task={t}/>;
    case 'task-reject':return <Reject key={key} task={t}/>;
    case 'task-transfer':return <Transfer key={key} task={t}/>;
    case 'task-transfer-response':return <Transfer key={key} task={t} response/>;
    case 'task-edit':case 'task-change':return <Requirements key={key} task={t}/>;
    case 'task-plan':case 'task-authorize':case 'task-budget':return <AssistantSetup key={`${t.id}:setup`} task={t}/>;
    case 'task-progress':return <Progress key={key} task={t}/>;
    case 'task-failure':return <Failure key={key} task={t}/>;
    case 'task-result':return <Result key={key} task={t}/>;
    case 'task-versions':return <Versions key={key} task={t}/>;
    case 'task-preview':return <Preview key={key} task={t}/>;
    case 'task-artifact-edit':return <Preview key={key} task={t} edit/>;
    case 'task-send':case 'task-send-confirm':return <TaskCommunication key={key} task={t} kind="消息"/>;
    case 'task-email':return <TaskCommunication key={key} task={t} kind="邮件"/>;
    case 'task-calendar':return <TaskCommunication key={key} task={t} kind="日程"/>;
    case 'task-receipt':return <Receipts key={key} task={t}/>;
    case 'task-history':return <History key={key} task={t}/>;
    case 'task-complete':return <Complete key={key} task={t}/>;
    case 'task-ask':return <Questions key={key} task={t}/>;
    case 'task-attachment':return <Supplement key={key} task={t}/>;
    case 'task-progress-note':return <ProgressNote key={key} task={t}/>;
    default:return <Empty title="入口暂时不可用" body="回到这项工作选择下一步" action="返回详情" onAction={()=>navigate({view:'task-detail',id:t.id})}/>;
  }
}
