import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {registerHooks,stripTypeScriptTypes} from 'node:module';
registerHooks({resolve(specifier,context,next){if(specifier.startsWith('.')&&context.parentURL?.startsWith('file:')){const url=new URL(specifier,context.parentURL);if(!/\.[a-z]+$/i.test(url.pathname))for(const ext of ['.ts','.tsx'])if(existsSync(new URL(url.href+ext)))return next(url.href+ext,context);}return next(specifier,context);}});
const url=p=>new URL(p,import.meta.url).href;
async function load(code){return import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(code,{mode:'strip'})).toString('base64'));}
const store=readFileSync(new URL('../src/store.tsx',import.meta.url),'utf8');
const {initialData}=await load(store.slice(store.indexOf('export function initialData')));
const home=readFileSync(new URL('../src/features/Home.tsx',import.meta.url),'utf8');
const imports=`import {sharedMemoryEligible} from '${url('../src/memoryAccess.ts')}';import {makeSourceReference,materialVisible,provenanceAvailable,sourceAvailable,taskSourceAvailable,taskVisible as scopedTaskVisible,sessionVisible as scopedSessionVisible} from '${url('../src/sourceAccess.ts')}';import {taskIsMyAttention} from '${url('../src/taskWorkflow.ts')}';`;
const model=await load(imports+home.slice(home.indexOf('export function homeTitle'),home.indexOf('export function Home()'))+home.slice(home.indexOf('type LocalAnswer'),home.indexOf('function referenceRoute'))+home.slice(home.indexOf('export function notificationVisible'),home.indexOf('export function Notifications')));
const {migrateStoredData}=await import('../src/stateMigrations.ts');
function stock(){const d=initialData(),t=d.tasks.find(t=>t.id==='TASK-032');t.needsReview=false;t.sourceNeedsReview=false;t.results=['旧库存999件'];t.artifacts=[{id:'old',kind:'资料',title:'旧库存',version:1,created:'昨天',body:['旧库存999件'],reviewedAt:'昨天',needsReview:false,sourceNeedsReview:true},{id:'new',kind:'资料',title:'已核对库存',version:2,created:'今天',body:['新库存18件'],reviewedAt:'今天',needsReview:false}];return d;}
test('revalidated task cannot reuse invalid retained artifact or legacy result',()=>{const d=stock();d.tasks.find(t=>t.id==='TASK-032').artifacts=d.tasks.find(t=>t.id==='TASK-032').artifacts.slice(0,1);assert.doesNotMatch(model.buildLocalAnswer('椅子库存',d,true).text,/999/);assert.equal(model.buildLocalAnswer('椅子库存',d,true).sources.length,0);});
test('inventory answer uses only a reviewed current-source artifact',()=>{const d=stock(),a=model.buildLocalAnswer('椅子库存',d,true);assert.match(a.text,/18件/);assert.doesNotMatch(a.text,/999/);d.tasks.find(t=>t.id==='TASK-032').artifacts[1].needsReview=true;assert.doesNotMatch(model.buildLocalAnswer('椅子库存',d,true).text,/18件/);});
test('raw words absent from summary are searchable and route to the exact turn',()=>{const d=initialData();d.sessions[0].transcript.push({id:'specific',time:'00:21:00',speaker:'我',text:'独特检索词 nebula42'});const rows=model.searchSavedContent(d,'NEBULA42','会话');assert.equal(rows.length,1);assert.equal(rows[0].route.mode,'specific');});
test('shared search cannot expose a private raw turn',()=>{const d=initialData();d.settings.space='Oops 产品团队';d.settings.toggles['shared-session-001']=true;d.sessions[0].transcript.push({id:'secret',time:'00:21:00',speaker:'我',text:'privateNeedle',private:true});assert.deepEqual(model.searchSavedContent(d,'privateNeedle'),[]);});
test('an unrelated question cannot cite an arbitrary first conversation',()=>{const a=model.buildLocalAnswer('想讨论银河旅行',initialData(),true);assert.equal(a.sources.length,0);assert.match(a.text,/哪段会话/);});
test('resolved memory and cancelled-task notifications are not active reminders',()=>{const d=initialData();d.memories.find(m=>m.id==='MEM-003').confirmed=true;assert.equal(model.notificationVisible(d,{view:'memory-conflict',id:'MEM-003'}),false);d.tasks[0].status='已取消';assert.equal(model.notificationVisible(d,{view:'task-detail',id:d.tasks[0].id}),false);});
test('migration binds only verified exact turns and archives stale completion',()=>{const d=initialData();delete d.sessions[0].transcript[1].personId;d.sessions[0].transcript.push({id:'same',time:'00:24:00',speaker:'Alex',text:'尚未核对'});d.tasks[0].completion={summary:'旧完成',date:'昨天',remaining:'',actor:'我'};d.tasks[0].due='2026/10/09 17:00';const m=migrateStoredData(d);assert.equal(m.sessions[0].transcript[1].personId,'p2');assert.equal(m.sessions[0].transcript.at(-1).personId,undefined);assert.equal(m.tasks[0].completion,undefined);assert.equal(m.tasks[0].completionHistory[0].summary,'旧完成');assert.equal(m.tasks[0].due,'2026-10-09T17:00');});
