import { createContext, useContext } from 'react';

export type Route = { view: string; id?: string; mode?: string };
export type Transcript = { id: string; speaker: string; time: string; text: string; private?: boolean; personId?: string };
export type Session = { id: string; title: string; kind: '会议'|'日常'|'灵感'|'练习'|'Recall'; date: string; duration: string; status: '进行中'|'暂停'|'已结束'|'待开始'; transcript: Transcript[]; summary: string[]; agenda: string[]; participants: string[]; attachments: string[]; privateNotes: string[]; project: string; archived?: boolean };
export type SourcePointer = { sourceSession?: string; sourceId?: string; sourceTime?: string };
export type SourceReference = { kind: 'session'|'task'|'memory'|'project'|'profile'; id: string; sourceId?: string; sourceTime?: string; version?: number; fingerprint?: string; profileScope?: 'identity'|'preferences' };
export type TaskArtifact = SourcePointer & { id: string; kind: '文档'|'PPT'|'资料'; title: string; version: number; body: string[]; created: string; needsReview?: boolean; sourceNeedsReview?: boolean; reviewedAt?: string; reviewHistory?: { version: number; reviewedAt: string }[]; sources?: SourceReference[] };
export type TaskMaterial = SourcePointer & { id: string; title: string; memoryId?: string; body?: string; note?: string; needsReview?: boolean };
export type TaskWorkKind = '行动'|'交付';
export type TaskOutputMode = '资料整理'|'回复草稿'|'行动清单'|'文档'|'文档与PPT'|'完整框架与PPT'|'仅提纲';
export type TaskScope = { sources: string; destination: string; space?: string; materialIds?: string[]; includeSource?: boolean };
export type TaskInquiry = { id: string; question: string; status: '待回答'|'已回答'|'已解决'; target?: string; answer?: string; nextFollowUp?: string; created?: string };
export type TaskTransferRequest = { id: string; fromOwner: string; fromStatus: Task['status']; to: string; status: '待回应'|'已同意'|'已婉拒'|'已撤回'; reason?: string; created?: string; nextFollowUp?: string };
export type TaskCompletion = { id: string; kind: '人工完成'|'交付验收'; summary: string; completedAt: string; artifactIds?: string[]; remaining?: string };
export type ArtifactBinding = SourcePointer & { id: string; version: number; fingerprint: string; title?: string; kind?: TaskArtifact['kind']; body?: string[]; sources?: SourceReference[]; sourceNeedsReview?: boolean };
export type TaskDraft = { target: string; body: string; attachments: string; subject?: string; cc?: string; account?: string; start?: string; end?: string; calendar?: string; artifactRefs?: ArtifactBinding[]; basedOnVersion?: number; sourceSnapshots?: SourceReference[]; taskSnapshot?: string; snapshotSpace?: string; versionChoice?: 'current'|'keep'|'updated'; replyToInquiryId?: string; recheckedTaskSnapshot?: string; artifactSelectionFingerprint?: string };
export type TaskGenerationSnapshot = { token: string; mode: TaskOutputMode; cost: number; version: number; space: string; scope: TaskScope; fingerprint: string; materialFingerprint: string; materials: TaskMaterial[]; sourceRefs: SourceReference[]; businessStatus: '已承接'|'进行中'; task: { id: string; title: string; description: string; owner: string; due: string; workKind: TaskWorkKind; criteria: string[]; questions: string[]; sourceSession?: string; sourceId?: string; sourceTime?: string } };
export type Task = SourcePointer & { id: string; title: string; description: string; owner: string; requester: string; due: string; priority: '高'|'中'|'低'; status: '待承接'|'已承接'|'进行中'|'待验收'|'已完成'|'已拒绝'|'待转交'|'已取消'; aiStatus: '未启动'|'待授权'|'准备中'|'已暂停'|'已停止'|'失败'|'草稿完成'; workKind?: TaskWorkKind; origin?: '本人创建'|'会话建议'|'他人交办'; relatedSessionId?: string; sourceMemoryId?: string; sourceMessageId?: string; sources?: SourceReference[]; needsReview?: boolean; sourceNeedsReview?: boolean; generationToken?: string; generationSnapshot?: TaskGenerationSnapshot; generationSources?: SourceReference[]; generationSpace?: string; scope?: TaskScope; outputMode?: string; criteria?: string[]; materials?: string[]; questions?: string[]; inquiries?: TaskInquiry[]; nextFollowUp?: string; completion?: TaskCompletion; completionHistory?: TaskCompletion[]; transferRequest?: TaskTransferRequest; artifacts?: TaskArtifact[]; deliveryArtifactIds?: string[]; materialRefs?: TaskMaterial[]; drafts?: Record<string,TaskDraft>; draftHistory?: { kind: string; draft: TaskDraft; date: string }[]; budget?: number; used?: number; failure?: string; retryMissing?: boolean; activities: string[]; results: string[]; authorized?: boolean; version: number; transferTo?: string };
export type Memory = SourcePointer & { id: string; title: string; body: string; category: '记忆'|'灵感'|'目标'|'模板'|'工作流'|'收藏'; tags: string[]; visibility: '私有'|'项目共享'; updated: string; confirmed: boolean; sources?: SourceReference[]; needsReview?: boolean; starred?: boolean; deleted?: boolean; revision?: { original: Transcript; action: 'edit'|'delete' } };
export type Person = { id: string; name: string; role: string; company: string; note: string; voice: boolean; shared: boolean };
export type Project = { id: string; name: string; description: string; members: string[]; budget: number; rule: string };
export type Receipt = { id: string; taskId: string; kind: string; target: string; body: string; date: string; space?: string; actor?: string; signature?: string; draftSnapshot?: TaskDraft; artifactRefs?: ArtifactBinding[]; start?: string; end?: string; calendar?: string };
export type AssistantMessage = { id: string; role: 'user'|'assistant'; text: string; space?: string; sourceSession?: string; sources?: SourceReference[]; invalidated?: boolean };
export type AppData = { sessions: Session[]; tasks: Task[]; memories: Memory[]; people: Person[]; projects: Project[]; receipts: Receipt[]; settings: { name: string; role: string; space: string; tone: string; toggles: Record<string,boolean>; connections: Record<string,boolean>; devices: Record<string,boolean>; retention: Record<string,string>; avatar: string }; activeSessionId?: string; recallCleared: boolean; notifications: {id:string;title:string;body:string;route:Route;read:boolean}[]; messages: AssistantMessage[] };
export type OopsContextValue = { data: AppData; update: (change: Partial<AppData>|((current:AppData)=>AppData))=>void; route: Route; navigate: (route: Route)=>void; back: ()=>void; toast: (text:string)=>void; reset: ()=>void; requestEnd: (sessionId:string)=>void };
export const OopsContext = createContext<OopsContextValue|null>(null);
export function useOops(){ const context=useContext(OopsContext);if(!context)throw new Error('Oops context missing');return context; }

export function initialData(): AppData {
return {
sessions:[
{id:'session-001',title:'产品头脑风暴',kind:'会议',date:'10月8日 10:00',duration:'18:24',status:'已结束',project:'Oops 首版',participants:['我','王宁','Alex','待确认'],agenda:['明确首版目标','会中资料如何返回','任务与执行边界'],attachments:['产品指标.xlsx','用户访谈摘要.pdf'],privateNotes:['我的重点是先把主流程跑通。'],summary:['首页以私人提问与开始记录为主入口。','会中检索结果作为资料卡回到相关议题，减少打断。','任务需要承接，助手执行与外部发送分别确认。'],transcript:[{id:'tr1',speaker:'我',time:'00:06:20',text:'先把我在这个项目里的角色和目标记住，后面给我的建议才有上下文。'},{id:'tr2',personId:'p2',speaker:'Alex',time:'00:12:40',text:'首版先按十万元预算，我们把最关键的使用链路做出来。'},{id:'tr3',speaker:'待确认',time:'00:16:28',text:'检索出来的资料先放在当前议题旁边，不要每次都打断。'},{id:'tr4',personId:'p1',speaker:'王宁',time:'00:18:02',text:'第三季度 KPI 复盘先给一版框架，再做六页 PPT，周五17点前给我。'},{id:'tr5',speaker:'我',time:'00:18:10',text:'请核实蓝色椅子B-108的库存，现货和预留分别列清楚，再准备跟进消息。'}]},
{id:'session-002',title:'桌面伙伴的灵感',kind:'灵感',date:'昨天 16:20',duration:'03:12',status:'已结束',project:'Oops 首版',participants:['我'],agenda:[],attachments:[],privateNotes:[],summary:['让桌宠用状态变化反馈正在听、正在想、等待确认。'],transcript:[{id:'in1',speaker:'我',time:'00:00:10',text:'桌面伙伴不需要一直说话，用一个抬头或者轻轻闪烁就能让我知道它在陪伴。'}]},
{id:'session-003',title:'首版体验走查',kind:'会议',date:'10月9日 14:00',duration:'',status:'待开始',project:'Oops 首版',participants:['我','Alex'],agenda:['录音到复盘','任务验收','记忆修订'],attachments:[],privateNotes:[],summary:[],transcript:[]}
],
tasks:[{id:'TASK-021',workKind:'交付',origin:'他人交办',title:'准备第三季度 KPI 复盘',description:'先整理目标、实际、差异与原因，再准备6页汇报PPT。缺少的数据先确认。',owner:'我',requester:'王宁',due:'2026-10-09T17:00',priority:'高',status:'待承接',aiStatus:'未启动',sourceSession:'session-001',sourceTime:'00:18:02',activities:['王宁从产品头脑风暴提出任务'],results:[],version:1},{id:'TASK-032',workKind:'行动',origin:'他人交办',title:'核实蓝色椅子库存',description:'核实SKU B-108的现货和可售数量，整理跟进消息。',owner:'我',requester:'Alex',due:'2026-10-08T18:00',priority:'中',status:'已承接',aiStatus:'草稿完成',sourceSession:'session-001',sourceTime:'00:18:10',activities:['已查询指定产品资料','库存结果等待人工确认'],results:['库存：24件；已预留：6件；可售：18件。数据更新时间10月7日18:00。'],authorized:true,version:1},{id:'TASK-033',workKind:'行动',origin:'会话建议',title:'验证会中资料卡的返回方式',description:'资料卡回到相关议题旁，验证是否减少打断。',owner:'我',requester:'我',due:'',priority:'中',status:'待承接',aiStatus:'未启动',sourceSession:'session-001',sourceTime:'00:16:28',activities:['从已保存建议生成待办草稿'],results:[],version:1}],
memories:[{id:'MEM-001',title:'我在 Oops 项目的角色',body:'负责首版产品体验与功能规划；给我的建议先说结论，再给依据。',category:'记忆',tags:['身份','Oops 首版'],visibility:'私有',updated:'今天',confirmed:true,sourceSession:'session-001',sourceTime:'00:06:20',starred:true},{id:'MEM-024',title:'会中资料卡如何返回结果',body:'让查到的资料留在相关议题旁边，需要时再打开；不把每个结果都变成主动打断。',category:'灵感',tags:['会中协助','待验证'],visibility:'私有',updated:'昨天',confirmed:true,sourceSession:'session-001',sourceTime:'00:16:28'},{id:'MEM-003',title:'我的职责是否发生变化？',body:'之前是团队协调，现在会议中提到由我负责首版产品规划。需要确认适用的项目与时间。',category:'记忆',tags:['待确认','身份'],visibility:'私有',updated:'今天',confirmed:false},{id:'MEM-004',title:'让表达更有结构',body:'每次讨论先说明结论、依据和下一步，每周回顾两段表达。',category:'目标',tags:['成长','表达'],visibility:'私有',updated:'本周',confirmed:true},{id:'MEM-005',title:'项目会议复盘',body:'会议目标 → 核心决议 → 待定问题 → 负责人 / 期限 → 下一步',category:'模板',tags:['会议'],visibility:'私有',updated:'昨天',confirmed:true},{id:'MEM-muyvilowp3e',title:'会后行动整理',body:'核对会议纪要\n确认负责人和期限\n检查待办成果',category:'工作流',tags:['会议'],visibility:'私有',updated:'今天',confirmed:true}],
people:[{id:'p1',name:'王宁',role:'业务负责人',company:'Oops 团队',note:'汇报前确认指标口径。',voice:true,shared:true},{id:'p2',name:'Alex',role:'设计与研发',company:'Oops 团队',note:'优先讨论体验与实现范围。',voice:true,shared:true},{id:'p3',name:'待确认',role:'未核对身份',company:'',note:'对应00:16:28的发言。',voice:false,shared:false}],
projects:[{id:'project-1',name:'Oops 首版',description:'把真实对话里的重要信息，转成能继续推进的行动。',members:['我','王宁','Alex'],budget:100000,rule:'先做可验证的主流程；对外操作逐项确认。'}],receipts:[],activeSessionId:undefined,recallCleared:false,
settings:{name:'林',role:'产品负责人',space:'我的空间',tone:'先结论，再给依据',toggles:{'speaker-confirmed:session-001:tr2':true,'speaker-confirmed:session-001:tr4':true,cloud:true,memory:true,voice:false,notifications:true,proactive:true,alwaysListen:false,location:false},connections:{飞书:false,邮箱:false,日历:false,资料库:false,电脑助手:false},devices:{录音豆:false,桌面伙伴:false},retention:{录音:'30天',转写:'180天',Recall:'5分钟'},avatar:'林'},
notifications:[{id:'n1',title:'跟进消息等你核对',body:'蓝色椅子库存 · 确认对象与完整正文',route:{view:'task-send',id:'TASK-032'},read:false},{id:'n2',title:'有一段声音身份待确认',body:'产品头脑风暴 · 00:16:28',route:{view:'session-identity',id:'session-001'},read:false},{id:'n3',title:'角色记忆需要更新',body:'核对你的项目职责和适用时间',route:{view:'memory-conflict',id:'MEM-003'},read:false}],messages:[]
};
}
