import { useId, type ReactNode } from 'react';
import { BottomSheet, Carousel, KeyboardInput, KeyboardTextarea, useKeyboard } from './mobile';

export function isTextEntryTarget(target: EventTarget | null): boolean {
  if (target instanceof HTMLTextAreaElement) return !target.disabled && !target.readOnly;
  return target instanceof HTMLInputElement && !target.disabled && !target.readOnly && ['text', 'search', 'email', 'tel', 'url', 'password', 'number'].includes(target.type);
}

export function Icon({name,size=22}:{name:string;size?:number}){return <img className="icon" src={`/icons/${name}.svg`} alt="" width={size} height={size} draggable={false}/>}
export function Button({children,onClick,tone='primary',disabled=false,type='button',icon}:{children:ReactNode;onClick?:()=>void;tone?:'primary'|'secondary'|'danger'|'quiet';disabled?:boolean;type?:'button'|'submit';icon?:string}){const keyboard=useKeyboard();return <button className={`button ${tone}`} onClick={()=>{keyboard.hide();onClick?.()}} disabled={disabled} type={type}>{icon&&<Icon name={icon}/>}<span>{children}</span></button>}
export function Card({children,className='',onClick}:{children:ReactNode;className?:string;onClick?:()=>void}){return onClick?<button className={`card clickable ${className}`} onClick={onClick}>{children}</button>:<section className={`card ${className}`}>{children}</section>}
export function Row({title,subtitle,icon='file-text',trailing,onClick,badge}:{title:string;subtitle?:string;icon?:string;trailing?:ReactNode;onClick?:()=>void;badge?:string}){const keyboard=useKeyboard();const content=<><span className="row-icon"><Icon name={icon}/></span><span className="row-copy"><strong>{title}</strong>{subtitle&&<small>{subtitle}</small>}</span>{badge&&<Badge>{badge}</Badge>}{trailing||(onClick?<Icon name="caret-right" size={18}/>:null)}</>;return onClick?<button className="list-row" onClick={()=>{keyboard.hide();onClick?.()}}>{content}</button>:<div className="list-row">{content}</div>}
export function Badge({children,tone='purple'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function SectionTitle({children,action,onAction}:{children:ReactNode;action?:string;onAction?:()=>void}){return <div className="section-title"><h2>{children}</h2>{action&&<button className="text-action" onClick={onAction}>{action}<Icon name="caret-right" size={14}/></button>}</div>}
export function Field({label,value,onChange,placeholder='',multiline=false,type='text',hint}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string;multiline?:boolean;type?:string;hint?:string}){const id=useId();const keyboard=useKeyboard();const blur=(next:EventTarget|null)=>{if(!isTextEntryTarget(next))keyboard.hide()};return <label className="form-field" htmlFor={id}><span>{label}</span>{multiline?<KeyboardTextarea id={id} aria-label={label} value={value} onChange={e=>onChange(e.target.value)} onBlur={e=>blur(e.relatedTarget)} placeholder={placeholder} rows={4}/>:<KeyboardInput id={id} aria-label={label} type={type} value={value} onChange={e=>onChange(e.target.value)} onBlur={e=>blur(e.relatedTarget)} onFocus={e=>{if(!isTextEntryTarget(e.currentTarget))keyboard.hide()}} placeholder={placeholder}/>} {hint&&<small>{hint}</small>}</label>}
export function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){const id=useId();const keyboard=useKeyboard();return <label className="form-field" htmlFor={id}><span>{label}</span><select id={id} aria-label={label} value={value} onPointerDown={()=>keyboard.hide()} onFocus={()=>keyboard.hide()} onChange={e=>{keyboard.hide();onChange(e.target.value)}}>{options.map((x,index)=><option key={`${index}:${x}`}>{x}</option>)}</select></label>}
export function Toggle({label,value,onChange,hint}:{label:string;value:boolean;onChange:(value:boolean)=>void;hint?:string}){return <label className="toggle-row"><span><strong>{label}</strong>{hint&&<small>{hint}</small>}</span><input aria-label={label} role="switch" type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/></label>}
export function Check({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <label className="check-row"><input aria-label={label} type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
export function Tabs({items,value,onChange}:{items:string[];value:string;onChange:(value:string)=>void}){const keyboard=useKeyboard();return <div className="segmented" role="tablist">{items.map(x=><button key={x} role="tab" aria-selected={value===x} onClick={()=>{keyboard.hide();onChange(x)}}>{x}</button>)}</div>}
export function Chips({items,value,onChange}:{items:string[];value:string;onChange:(value:string)=>void}){return <Carousel ariaLabel="筛选" className="chip-carousel" contentClassName="chip-track">{items.map(x=><button className={`chip ${value===x?'selected':''}`} key={x} aria-pressed={value===x} onClick={()=>onChange(x)}>{x}</button>)}</Carousel>}
export function Empty({title,body,action,onAction,icon='tray'}:{title:string;body:string;action?:string;onAction?:()=>void;icon?:string}){return <div className="empty-state"><span><Icon name={icon} size={32}/></span><h3>{title}</h3><p>{body}</p>{action&&<Button onClick={onAction} tone="secondary">{action}</Button>}</div>}
export function Sheet({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){return <BottomSheet open={open} onOpenChange={v=>{if(!v)onClose()}} title={title}><div className="sheet-content">{children}</div></BottomSheet>}
export function Notice({children,tone='soft'}:{children:ReactNode;tone?:string}){return <div className={`notice ${tone}`}>{children}</div>}
export function Avatar({name}:{name:string}){return <span className="avatar">{name.slice(0,1)}</span>}
export function Search({value,onChange,placeholder='搜索'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){const keyboard=useKeyboard();return <div className="search-input"><Icon name="magnifying-glass" size={18}/><KeyboardInput aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} onBlur={e=>{if(!isTextEntryTarget(e.relatedTarget))keyboard.hide()}} placeholder={placeholder}/>{value&&<button aria-label="清除搜索" onClick={()=>onChange('')}><Icon name="x" size={16}/></button>}</div>}
export function Source({title,time,onClick}:{title:string;time?:string;onClick?:()=>void}){return <button className="source-link" onClick={onClick}><Icon name="quotes" size={16}/><span>{title}{time&&` · ${time}`}</span><Icon name="arrow-up-right" size={14}/></button>}
